### ISSUE TITLE
Unraid only downloads on first startup

### ISSUE THREAD

**Issue by Catacas** [Inrixia/Floatplane-Downloader#101]
Hi,
I've got another probleem with docker and unraid. 
I'm still running in dev, because of the issue two days ago.
When I start the container it downloads all the newest videos. But it doesn't download new ones when it is running. At some point I get this error in the logs.
![image](https://user-images.githubusercontent.com/9129041/140476238-75f656e0-818e-475a-a73e-3ccf6f0045ec.png)

**Comment by Inrixia** [comment]
This is a issue with floatplanes notification system. I'll have to change away from it if they dont get back to me on why its broken.

Thanks for reporting this. For now you can set a chron job to auto restart and that should allow new videos to download.

**Comment by Catacas** [comment]
ok! Thanks for the quick response!

**Comment by Inrixia** [comment]
This should be fixed in https://github.com/Inrixia/Floatplane-Downloader/commit/8159d118311398c1d957ee91c084f69636d988bb

Feel free to test it on dev. I'm aiming to merge dev and get a release out with all its changes soon

**Comment by Catacas** [comment]
can confirm! It is working thanks for the quick fix!
