### ISSUE TITLE
More info to help solve text glitching

### ISSUE THREAD

**Issue by kamiyo** [Inrixia/Floatplane-Downloader#102]
Hi, mpb author here:

In `Downloader.ts`, does `args.headless` affect whether you print or not? I couldn't tell whether `headless` referred to not printing any bars, or something else. My first suspicion is that `updateSummaryBar()` is being called, and that will mess up the printing of mpb, since it will push the bars up a bit, and then mpb will redraw the whole screen, so it will look like it's jumping.

Also, just checking, is `summaryStats` ever `undefined`? Here, it checks for it being `undefined`, but it's initialized to `{}` so it will never be `undefined`:
https://github.com/Inrixia/Floatplane-Downloader/blob/4fa0c461f23cebff5957d9c6a25ab0e674926b1c/src/Downloader.ts#L62

If you want a status-bar like thing, mpb has "borders" that you can put text in, so that can act as a status-bar.

https://github.com/kamiyo/multi-progress-bars/issues/5

**Comment by Inrixia** [comment]
Hey. `args.headless` is for many things but yes one of the things it does is completely disable using progress bars and switches back to normal console use, this is for inside docker containers etc where console spam would be problematic.

It's possible that the `summaryBar` could be causing the issues when there is not enough space for it to print as you say. Though without the ability to pin a bar to the bottom to show summary info not sure how it could be fixed.

If it is the `summaryBar` then having the ability to remove completed bars should fix it for most cases. And those where there are enough download threads to cause the issue with incomplete bars would just have to live with it.

**Comment by Inrixia** [comment]
This should be fixed in https://github.com/Inrixia/Floatplane-Downloader/commit/1544d740495360352ebb1dc761b42c2e686f8b84! Please test it if you get the chance and get back to me

**Comment by Inrixia** [comment]
I'm gonna close this since its so old. Please let me know if its still a issue
