### ISSUE TITLE
Implement whitelisting from automatic deletion of aged videos

### ISSUE THREAD

**Issue by vodkapmp** [Inrixia/Floatplane-Downloader#103]
As mentioned in issue #56, removing videos over x amount of days would be nice if it was per channel/creator.

I would prefer a way to whitelist channels from being deleted after x days age, but I can see people wanting custom days per channel/creator.

**Comment by Inrixia** [comment]
This should be completely working in https://github.com/Inrixia/Floatplane-Downloader/commit/04415a23bd3da67be98adcedb19fb57674e6e9db

Note that this contains breaking changes and deletion will not work with videos downloaded prior to updating. When updating the `daysToKeepVideos` setting will not be deleted but will also no longer affect anything, a `daysToKeepVideos` setting will appear on all subchannels which you can customise to your liking.

**Comment by Inrixia** [comment]
@vodkapmp If you get the chance please test this on the beta channel.
