### ISSUE TITLE
Feature request for downloading based on filter

### ISSUE THREAD

**Issue by Frooodle** [Inrixia/Floatplane-Downloader#115]
My usecase is that I want to download all their exclusive content so that I can watch it without needing to be connected to internet.
as far as i can tell the only way of doing this is downloading their whole library and filtering after the download.

Instead can I tell it to download only if contains the keywork 'Exclusive' etc?

**Comment by Inrixia** [comment]
Hey, I presume you figured this out but adding it here for anyone who stumbles upon this.

Every subscription has a default subchannel that all videos go into. You can set this default subchannel to be skipped and then create a custom subchannel with the filters you want. 
Details for it all are in the settings wiki here:

https://github.com/Inrixia/Floatplane-Downloader/blob/master/wiki/settings.md

If you or anyone who comes across this has questions feel free to ask here.
