### ISSUE TITLE
Error trying to download

### ISSUE THREAD

**Issue by Prouser123** [Inrixia/Floatplane-Downloader#12]
Hi, whenever I run the float.js script it keeps exiting with this error:

```
An error occurred: connect ECONNREFUSED 144.217.49.155:443 { Error: connect ECONNREFUSED 144.217.49.155:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '144.217.49.155',
  port: 443 } undefined
```

I have a feeling it might be CloudFlare blocking the request because there were too many requests sent and it thinks it could be an attack. Any ideas?

**Comment by Inrixia** [comment]
Considering I have had the script download a lot of videos before I doubt its being blocked, generally mass requests from one IP just get slowed down for 30 seconds. This looks like some other issue... Perhaps try using a different floatplane server in the settings? Though I cannot vouch for if that still works as I believe there may have been a issue with it.

As you said its definitely external to the script, Can you check if you are able to download videos normally yourself?

**Comment by Inrixia** [comment]
You have to set autoFetchServer to false or it will get your recommended server automatically. I think that you might need to try the US server to see if its a issue with whatever your default one is. I cannot remember if I tested the script properly for some regions last time stuff regarding that was updated.


Info about the settings is all in:
https://github.com/Inrixia/Floatplane-Downloader/blob/master/wiki/settings.md

**Comment by Prouser123** [comment]
I've disabled autoFetchServer and manually set the server address, but now all it does is create a 1kb file and mark the download as complete.

This is what i'm getting with the downloads, and my server is set to ```https://Edge01-eu.floatplaneclub.com```
```
Linus Tech Tips> Intel Graphics Cards in [                              ] 100% 0/0MB
Linus Tech Tips> Computer Virus outbreak [                              ] 100% 0/0MB
Linus Tech Tips> The Fitness PC! [                              ] 100% 0/0MB
Techquickie> TQ iOS 12 Explained [                              ] 100% 0/0MB
Linus Tech Tips> Is the MacBook Pro 2018 [                              ] 100% 0/0MB
Linus Tech Tips> Mouth-Operated Mouse! [                              ] 100% 0/0MB
Floatplane Exclusive> FP Exclusive Oregon Tra [                              ] 100% 0/0MB
Linus Tech Tips> BlackBerry KEY2 Review [                              ] 100% 0/0MB
Linus Tech Tips> Philips 436M6 Review [                              ] 100% 0/0MB
Linus Tech Tips> The BIGGEST Notch! [                              ] 100% 0/0MB
```

**Comment by Inrixia** [comment]
Not sure whats up with it. My internets currently down so I cant test it till later... I think that they might have changed something with the api which is causing things to break.

**Comment by Prouser123** [comment]
Just tried running it again by clearing videos.json and partial.json, and now I'm back to the same issue as before.

Here is the output:
```
serv01@Serv01:~/DownloadScripts/Floatplane$ node float.js
> Using saved login data
> Cookie Constructed!
> Using saved subscriptions
> Fetching video key
Fetched! Using Server [https://Edge01-na.floatplaneclub.com]
> Saving settings


=== Episode Count ===
Floatplane Exclusive: 0
Linus Tech Tips: 0
Techquickie: 0


=== Linus Tech Tips - Page 0 ===
>-- This PC Case FLIES! == DOWNLOADING
>-- NVIDIA RTX 2080 DROPPING NEXT WEEK! == QUEUED
>-- Backing Up the Petabyte Server == QUEUED
>-- TQ What is Creative Commons == QUEUED
>-- Intel Graphics Cards in 2020! == QUEUED
>-- The Fitness PC! == QUEUED
>-- Is the MacBook Pro 2018 REALLY Bad == QUEUED
>-- FP Exclusive Oregon Trail Let's Play! == QUEUED
>-- 'HDR' Finally MEANS Something! - Philips 436M6 Review == QUEUED
>-- Geforce RTX The FUTURE is Ray Tracing == QUEUED
>-- Powerful PC in your POCKET - GPD Pocket 2 Review == QUEUED
>-- TQ Do You Still Need a Mousepad == QUEUED
>-- Chilling Threadripper 2!!! == QUEUED
>-- SteamTV Takes On Twitch! == QUEUED
>-- Don't Waste $1000 on Data Recovery - DeepSpar Tour (SPONSORED) == QUEUED
>-- TQ How Secure is Incognito Mode == QUEUED
>-- Troubleshooting the $100,000 PC - Livestream Archive == QUEUED
>-- Get an Xbox for 35 bucks! (a month!) == QUEUED
>-- Use ANY Controller Lag-Free Over USB! == QUEUED
>-- Why does Linus PIRATE Windows == QUEUED


=== Linus Tech Tips - Page 1 ===
>-- TQ How Does Spotify Work == QUEUED
>-- TL ZEN + VEGA...in a Chinese Console! == QUEUED
>-- Microsoft Surface Go - Classic LIVE Unboxing == QUEUED
>-- Scrapyard Wars 7 No Internet Finale! == QUEUED
>-- Does Razer Still Have It - Blade 2018 Review == QUEUED
>-- Downloading Games at 10 GIGABIT == QUEUED
>-- Computer Virus outbreak DELAYS the new iPhone == QUEUED
>-- TQ iOS 12 Explained == QUEUED
>-- Mouth-Operated Mouse! == QUEUED
>-- I used this for a MONTH ☹ - BlackBerry KEY2 Review == QUEUED
>-- Google Pixel 3 XL - The BIGGEST Notch! == QUEUED
>-- Worst Day Ever. - Samsung Galaxy Note9 Hands on == QUEUED
>-- TQ What's the Difference Between Monitors and TVs == QUEUED
>-- Discord Store TAKES ON STEAM! == QUEUED
>-- We Ran INTEL Optane on an AMD CPU! == QUEUED
>-- Building the $100,000 PC Pt. 2 - PCIe Splitter Backplane == QUEUED
>-- The Workstation of the Future is HERE! - Threadripper 2nd Gen == QUEUED
>-- U.S.-China Tariffs Claim 1st Victim ( == QUEUED
>-- An Open Source CPU! == QUEUED
>-- TQ Why Do We Still Need Cable Boxes == QUEUED
An error occurred: connect ECONNREFUSED 144.217.49.155:443 { Error: connect ECONNREFUSED 144.217.49.155:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '144.217.49.155',
  port: 443 } undefined
```

Do you think it might be due to it constantly attempting to switch regions?

**Comment by lishan89uc** [comment]
Hmm this just started happening to me too...

**Comment by lishan89uc** [comment]
UPDATE: Kind of fixed it but more like a workaround I guess... I did what Inrixia said "You have to set autoFetchServer to false" and then i changed the server to https://Edge02-na.floatplaneclub.com

**Comment by Prouser123** [comment]
I tried this on the EU servers, and got
```
> Using saved login data
> Cookie Constructed!
> Using saved subscriptions
> Fetching video key
Fetched! Using Server [https://edge02-eu.floatplaneclub.com/]
> Saving settings
=== Episode Count ===

=== Linus Tech Tips - Page 0 ===
>-- 'HDR' Finally MEANS Something! - Philips 436M6 Review == DOWNLOADING
>-- Geforce RTX The FUTURE is Ray Tracing == QUEUED
>-- Powerful PC in your POCKET - GPD Pocket 2 Review == QUEUED
>-- TQ Do You Still Need a Mousepad == QUEUED
>-- Chilling Threadripper 2!!! == QUEUED
>-- SteamTV Takes On Twitch! == QUEUED
>-- Don't Waste $1000 on Data Recovery - DeepSpar Tour (SPONSORED) == QUEUED
>-- TQ How Secure is Incognito Mode == QUEUED
>-- Troubleshooting the $100,000 PC - Livestream Archive == QUEUED
>-- Get an Xbox for 35 bucks! (a month!) == QUEUED
```
... and then just a bunch of line breaks. I also ran it on both NA servers and got:
```Linus Tech Tips> 2-in-1 Convertible GAMI [     ] 100% 0/0MB```
for every video. It does manage to download the thumbnail but the video file is only 1KB in size.

Also, they have changed the UI a bit for watching videos now so that could be a problem if their API is different.

Looking at the console logs for the website it looks like I'm not connecting to any EU servers, despite them being online and accessible through a web browser. The console log for the videos page is below.

![image](https://user-images.githubusercontent.com/20697043/44840170-6e17ce00-ac38-11e8-8e80-57c9cac228f5.png)

**Comment by Inrixia** [comment]
Can't debug until tomorrow at the earliest. Just moved house, sorry. It's probably due to api changes.

**Comment by Prouser123** [comment]
No problem, I saw that on Discord, just thought it was worth sharing.

**Comment by Inrixia** [comment]
Edge01 servers on floatplane appear to no longer work. I have changed the script to force Edge02 servers, and dynamic server fetching for regions will still work with this. Should be fixed.

Commit [https://github.com/Inrixia/Floatplane-Downloader/commit/7a00ad4b28e7ef5a9686fb90272486e13d0d76c8](https://github.com/Inrixia/Floatplane-Downloader/commit/7a00ad4b28e7ef5a9686fb90272486e13d0d76c8)
