### ISSUE TITLE
Picture and Text posts not being filtered and downloader throws an error when encountering them

### ISSUE THREAD

**Issue by Hezkezl** [Inrixia/Floatplane-Downloader#120]
As per conversation in Discord, https://cdn.discordapp.com/attachments/468978648460820490/1000099283959287910/unknown.png this picture shows that the downloader is running into problems with these three posts.

https://www.floatplane.com/post/Tqphjp3rHv (HDR Feedback / Bug Reports)
https://www.floatplane.com/post/fOGeGyd3vW (Waiting for something? Need a pet distraction?)
https://www.floatplane.com/post/XGjHDKHSGr (HDR Complications - To explain things a bit (Text post))

**Comment by Hezkezl** [comment]
For anyone encountering this and wanting a temporary fix, you can add this to your settings.json file for a channel that you're skipping (I'm skipping Carpool Critics, so I just added this in that section)

				"Carpool Critics": {
					"title": "Carpool Critics",
					"skip": true,
					"identifiers": [
						{
							"check": "CC: ",
							"type": "title"
						},
						{
							"check": "'Carpool Critics' ",
							"type": "title"
						},
						{
							"check": "Wanted: HDR Feedback - Video: Are CRTs Dead",
							"type": "title"
						},
						{
							"check": "HDR Feedback / Bug Reports",
							"type": "title"
						},
						{
							"check": "Waiting for something? Need a pet distraction?",
							"type": "title"
						},
						{
							"check": "HDR Complications - To explain things a bit (text post)",
							"type": "title"
						}
					],
					"daysToKeepVideos": -1
				},

**Comment by Inrixia** [comment]
I beleive this is due to api changes and thus will need updated to be made to https://github.com/Inrixia/floatplaneAPI.ts

I'm already working on this

**Comment by Inrixia** [comment]
This should be fixed on dev
