### ISSUE TITLE
Arm Support

### ISSUE THREAD

**Issue by jozefbonnar** [Inrixia/Floatplane-Downloader#122]
It would be nice to support Arm as my nas is running arm and the docker image is not supported, i'm running linux/arm64/v8 and it just shows "exec /usr/local/bin/docker-entrypoint.sh: exec format error"

**Comment by Inrixia** [comment]
Looks like there is support for arm for most things this project uses, but I don't have a arm device to easily test setting up a arm so many need help from others on this

**Comment by Inrixia** [comment]
@jozefbonnar Would you be free to test a arm build in discord?

**Comment by jozefbonnar** [comment]
Sure

**Comment by Inrixia** [comment]
The latest dev image on [DockerHub](https://hub.docker.com/r/inrix/floatplane-downloader/tags) now has `arm64` and `amd64`. Can you please pull this and try it?

**Comment by jozefbonnar** [comment]
It all works great! Thank you for adding support for arm
