### ISSUE TITLE
Embed Thumbnail

### ISSUE THREAD

**Issue by Dragonlord1005** [Inrixia/Floatplane-Downloader#124]
I believe their is a functionality in ffmpeg that allows you to embed thumbnails into videos, this would be a great functionality to have in my opinion

**Comment by Inrixia** [comment]
Looks like this is possible. https://stackoverflow.com/questions/54717175/how-do-i-add-a-custom-thumbnail-to-a-mp4-file-using-ffmpeg

**Comment by Inrixia** [comment]
Done in https://github.com/Inrixia/Floatplane-Downloader/commit/e9b67a7d3530895a1505799361178ecf43043fcc

This is live on dev now
