### ISSUE TITLE
Response code 400 (Bad Request)

### ISSUE THREAD

**Issue by VioletLovesJasmine** [Inrixia/Floatplane-Downloader#130]
Hi, I'm having some issues downloading videos since 2022-09-25.

Everything worked fine for ages, then the log showed an error that 'package.json' was missing. This file was not previously required (only the binary), but I found the 'package.json' in your repo and that error now seems to be resolved. This is included more as a possibly related side-note.

The second, unresolved error happens when the program actually tries to download the videos. The log shows 'Response code 400 (Bad Request)'. Exemplary shell output is attached. Changing around network settings and disabling VPN did not help. I also tried regenerating ./db/ and other related objects in case it was something to do with login. The attached log shows a freshly generated login and settings.json.

Any idea what could be causing this?

[output.log](https://github.com/Inrixia/Floatplane-Downloader/files/9679394/output.log)

**Comment by Inrixia** [comment]
Re discussion in discord floatplane appears to have just made breaking changes to their api.

I should be able to update and fix this on dev as soon as I get home in ~5-6 hrs

**Comment by Inrixia** [comment]
Oh also the package.json error has already been fixed on dev so once those changes are released you won't need to use that fix

**Comment by VioletLovesJasmine** [comment]
ah ok, thanks for your work :)

**Comment by Inrixia** [comment]
Please try the latest dev release and let me know if this is fixed

**Comment by VioletLovesJasmine** [comment]
Now using latest dev release. Mostly fine now, still seeing some errors though. Maybe 20% of videos this happens:
`ChannelSuperFun - CSF: I fought : [spaces] 0% | ERR: read ECONNRESET Max Retries! 3/3`

I tried rerunning after it had finished downloading and it seemed to work for some of them after more retries.
`ChannelSuperFun - CSF: I fought : ██████▌ [spaces] 16% | 92.62/563.74MB 9.25Mb/s ETA: 6m 47s`

Not others though
`Linus Tech Tips - AMD Ryzen 7000: [spaces] 0% | ERR: read ECONNRESET Max Retries! 3/3`

**Comment by VioletLovesJasmine** [comment]
I tried running it again (later) and 'ECONNRESET' doesn't seem to be happening now. I'm not sure what changed.
