### ISSUE TITLE
Plex scan occurs on every check

### ISSUE THREAD

**Issue by mattkdoggie** [Inrixia/Floatplane-Downloader#133]
When new videos are checked, even when no new videos are found the related Plex library is scanned. 
This causes unnecessary scanning when they is no videos for it to find.

**Comment by Inrixia** [comment]
This should be fixed in https://github.com/Inrixia/Floatplane-Downloader/commit/c94402762aa071abe3318881591db75a3d67ec8a please grab the latest dev release and check

**Comment by mattkdoggie** [comment]
Looks like it's fixed for me!
