### ISSUE TITLE
(Feature request) uNRAID community plugin

### ISSUE THREAD

**Issue by pkostadinov90** [Inrixia/Floatplane-Downloader#134]
Hi.

It would be amazing to have a community plugin for unraid. It's a simple predefined list of variable for the docker run command, with some description, that are available to the user to change. I can share if needed what I have setup so far, but it's probably way too basic.

And it would also be amazing if this gets tested under this specific scenario. I am personally having troubles setting up the permissions correctly, the docker writes as root, with 700, and I would like either to have it 755, or write as different user. And after many attempts to fix it, I never got this working, so I ended up creating a hourly cron to fix the permissions.

**Comment by Inrixia** [comment]
This has been a ongoing request with people having worked on it in the past. Unfortunately I don't run unraid so can't test any implementation.

If you or someone else can then I would be happy to work with them on providing it as a option.

**Comment by mattkdoggie** [comment]
I can share my setup if that would help.

**Comment by Inrixia** [comment]
That would be much appreciated @mattkdoggie

**Comment by mattkdoggie** [comment]
Here it is, for some reason Github won't let me upload the xml so I zipped it.
[floatplane-downloader.xml.zip](https://github.com/Inrixia/Floatplane-Downloader/files/10108700/floatplane-downloader.xml.zip)

**Comment by orthanc42** [comment]
![image](https://user-images.githubusercontent.com/13221583/204444372-165bcbdc-e006-455e-8852-bb310f3ca31c.png)
you might need to set the PGID, PUID, and UMASK on the docker container. i think i might've had to manually create those parameters inside the unraid docker interface. this lets docker set the right user id and group id on the abc user inside the container.

**Comment by Inrixia** [comment]
@pkostadinov90 Can you try what @orthanc42 suggested and let me know if that fixes permissions?

**Comment by pkostadinov90** [comment]
On a separate note, I would like to share what additional variables I use, I am not sure how to generate the XML file, so I will just drop the variables I am using, that were not in the provided XML by @mattkdoggie:

- floatplane_videoResolution
- floatplane_forceFullSearch
- floatplane_videosToSearch
- downloadThreads
- plex_sectionsToUpdate
- plex_token

**Comment by mattkdoggie** [comment]
Not sure about the problems with PUID and PGID as they seem to be working for me. I updated the XML to include a bunch of the most important variables. 
[floatplane-downloader.xml.txt](https://github.com/Inrixia/Floatplane-Downloader/files/10128826/floatplane-downloader.xml.txt)
