### ISSUE TITLE
Running float-win.exe for the first time results in a DeprecationWarning

### ISSUE THREAD

**Issue by PicoPlanetDev** [Inrixia/Floatplane-Downloader#138]
When I run the latest (v5.6.0) float-win.exe binary for the first time, I get the following output:
```
> Ffmpeg binary missing! Downloading... (node:15092) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `float-win --trace-deprecation ...` to show where the warning was created)
read err Error: too many length or distance symbols
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17) {
  errno: -3,
  code: 'Z_DATA_ERROR'
}
```
Running it using the suggested command `float-win --trace-deprecation` doesn't seem to do anything, unless I am not correctly using the command (quite possibly the case as well).

No rush on this issue right now though! If I find a workaround, I'll post it here.

**Comment by PicoPlanetDev** [comment]
It appears that there is some issue with the ffmpeg it downloads. My current workaround is to put an `ffmpeg.exe` binary in the `db` folder, which lets it start right up.

**Comment by PicoPlanetDev** [comment]
I seem to have figured out the problem - Floatplane Downloader was downloading a version of ffmpeg.exe that was incompatible with my machine. I'm not sure why, I'm on a 64 bit AMD processor. Anyway, as detailed above, running the downloader once and then replacing ffmpeg.exe with a binary from ffmpeg's website fixes the problem. Will leave this open unless Inrixia would like me to mark it solved for now.

**Comment by Inrixia** [comment]
ffmpeg download seems to be working fine on the latest dev version which has updated packages. Will close for now, if anyone else encounters this issue on a version after 5.6.0 please re-open.
