### ISSUE TITLE
Add the ability to download specific videos when providing their link

### ISSUE THREAD

**Issue by DasherPack** [Inrixia/Floatplane-Downloader#140]

**Comment by Inrixia** [comment]
Added in https://github.com/Inrixia/Floatplane-Downloader/commit/1dcded9164dc91c05be5f05b94b4d7479009d414, doesn't use URL's but the video id which is just the end bit of the url.

**Comment by Yannickclae** [comment]
This doesnt seem to work for me. It just tries to fetch new videos, and the videoID is removed from the settings.json file.

**Comment by Inrixia** [comment]
@Yannickclae can you give me a link to the video you are trying and copy the entire list/array/property your adding its guid to in your settings file?
