### ISSUE TITLE
[Docker] ERR: certificate has expired - Retrying

### ISSUE THREAD

**Issue by QuintonAjStevens** [Inrixia/Floatplane-Downloader#141]
Hello! I wanted to post this in case anybody else was having this issue with the docker container. I've removed my container completely and wiped the image, and wiped all my configurations to start completely fresh. After downloading the image and setting up my environment variables (I'm using docker on a Synology NAS), I am still getting the "ERR: certificate has expired - Retrying" error that doesn't clear and ends up reaching max retries. 

I've verified my subscription is active as well. It looks like it's downloading some files like the thumbnail and metadata, but only gets 0KB partial downloads of the video file itself. Is this a known issue?

**Comment by QuintonAjStevens** [comment]
Apologies for closing, I keep accidentally clicking buttons :)

**Comment by QuintonAjStevens** [comment]
Just verified, it also happens on a fresh install of the latest dev build in docker

**Comment by orthanc42** [comment]
the staff at floatplane has an expired SSL certificate setup on the edge download servers. nothing you can do other than wait for them to fix it. its not an issue with the docker.

**Comment by QuintonAjStevens** [comment]
> the staff at floatplane has an expired SSL certificate setup on the edge download servers. nothing you can do other than wait for them to fix it. its not an issue with the docker.

Ah okay thank you! I took a look at the front-end UI and also cannot download from there. Browser console suggests expired cert like you said.
