### ISSUE TITLE
[Feature suggestion] Show un-downloaded videos

### ISSUE THREAD

**Issue by TakenMC** [Inrixia/Floatplane-Downloader#144]
This I assume shouldn't be an issue not sure tho.

Could you make it show videos that are not yet being downloaded in the output if you have more videos selected to download then the download threads set.

Cause I want to download 6 videos but have 2 threads set so it doesn't limit me, so  having the videos that are queued would be nice.

**Comment by Inrixia** [comment]
Should be done, please test on latest dev branch and let me know if you have any issues.
