### ISSUE TITLE
[Feature suggestion] Better download check

### ISSUE THREAD

**Issue by TakenMC** [Inrixia/Floatplane-Downloader#146]
When I would have the video fail to download due to timeout or other issues when I close and reopen the program later it sees the video as downloaded and won't try again.

Could you add a way to either check on app launch or a flag that would force download videos that failed.

**Comment by Inrixia** [comment]
@TakenMC feel free to re open this if you feel it's still a issue. Or to ask questions here

**Comment by TakenMC** [comment]
kk ty for the info i didnt know that was how it worked
