### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AluminiumTech** [Inrixia/Floatplane-Downloader#15]
Hi,
I just wanted clarification, what license does this project/repo use?

I didn't see any license file in the repo so I'm assuming it's licensed under the copyright of the author.

Would appreciate it if it was open source as opposed to the current "code available" status.

**Comment by Inrixia** [comment]
I have added a licence and changed the readme to reflect it. Should all be fairly obvious now, Ill update the form post with the readme snippet too.
