### ISSUE TITLE
Socket hang up

### ISSUE THREAD

**Issue by rob1998** [Inrixia/Floatplane-Downloader#16]
So my docker creation stopped working a while ago, getting lots of these errors:
```
{ Error: socket hang up
at createHangUpError (_http_client.js:331:15)
at TLSSocket.socketCloseListener (_http_client.js:363:23)
at emitOne (events.js:121:20)
at TLSSocket.emit (events.js:211:7)
at _handle.close (net.js:557:12)
at TCP.done [as _onclose] (_tls_wrap.js:356:7) code: 'ECONNRESET' }
An error occurred: connect ECONNREFUSED 144.217.49.155:443 { Error: connect ECONNREFUSED 144.217.49.155:443
at Object._errnoException (util.js:992:11)
at _exceptionWithHostPort (util.js:1014:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: 'ECONNREFUSED',
errno: 'ECONNREFUSED',
syscall: 'connect',
address: '144.217.49.155',
port: 443 } undefined
```

Don't know yet if it has to do with the fact that it's running as a Docker image, it's using exactly the same script at the latest version (at the moment of writing this 4.2.8).
I already tried several things, like pinging the address it's hanging up on from the docker console, but that seems to be working fine.

So I would like to know if anyone has encountered this on a "normal" installation, or if you have any ideas?

**Comment by Prouser123** [comment]
Are you using edge01 servers? They stopped working a while ago and the defaults are now edge02.

**Comment by Inrixia** [comment]
Update to the latest version and it will be fixed. The reason for the hangup is in the release notes. Basically the Edge01 floatplane servers dont work anymore for some reason.

**Comment by rob1998** [comment]
Tried that, didn't work. As far as I can see it can find the videos. But when it tries to download them, the error occurs. Anyway I could send you some more info (from the logs) tomorrow.

**Comment by Inrixia** [comment]
Can you download a video off the actual site and see what server it has you use.

**Comment by Inrixia** [comment]
Also have you tried doing a clean install with the new docker version? Including wiping settings.

**Comment by rob1998** [comment]
It has been running since last night and managed to grab the FP Exclusive Meet the Team - Dennis video
but the rest is still not downloading, I am now getting the following error message, which I've seen before already:
```
{ Error: getaddrinfo EAI_AGAIN pbs.floatplanecdn.com:443
at Object._errnoException (util.js:992:11)
at errnoException (dns.js:55:15)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
code: 'EAI_AGAIN',
errno: 'EAI_AGAIN',
syscall: 'getaddrinfo',
hostname: 'pbs.floatplanecdn.com',
host: 'pbs.floatplanecdn.com',
port: 443 }
{ Error: socket hang up
at createHangUpError (_http_client.js:331:15)
at TLSSocket.socketCloseListener (_http_client.js:363:23)
at emitOne (events.js:121:20)
at TLSSocket.emit (events.js:211:7)
at _handle.close (net.js:557:12)
at TCP.done [as _onclose] (_tls_wrap.js:356:7) code: 'ECONNRESET' }
```

I've done some googling of my own, found that it might be a DNS/internet problem, but everything else works fine and I tried multiple dns servers already

Downloading through the floatplane website gives me the https://Edge02-na.floatplaneclub.com server

**Comment by Inrixia** [comment]
Can you see if using the script outside docker gives you the same issue?

**Comment by rob1998** [comment]
Okay on the new install:
Installed 4.2.8 freshly on a Windows 10 machine, logged in and it worked, but only kinda:
getting the following error in console:
```
{ Error: connect ETIMEDOUT 104.28.30.121:443
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1194:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.28.30.121',
  port: 443 }
{ Error: connect ETIMEDOUT 104.28.30.121:443
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1194:14)
  errno: 'ETIMEDOUT',
```

Turned on logging as wel, it logged this:
```
 == UNHANDLED ERROR > Error: connect ETIMEDOUT 104.28.30.121:443
```

Tested with the config for the new install on the server as well, but that one kept getting the error mentioned in my previous comment. Server runs in Docker on Unraid by the way. Only difference in config is the amount of videos to be downloaded and the fact that the server has the script set to repeating.

My current config:
```
{
  "version": "4.2.8",
  "videoFolder": "./videos/",
  "maxVideos": 5,
  "maxParallelDownloads": -1,
  "downloadArtwork": true,
  "formatWithEpisodes": false,
  "formatWithDate": true,
  "downloadUpdateTime": 250,
  "ignoreFolderStructure": false,
  "yearsAsSeasons": false,
  "monthsAsSeasons": false,
  "subscriptions": [
    {
      "id": "59f94c0bdd241b70349eb72b",
      "title": "Linus Tech Tips",
      "enabled": true,
      "ignore": {
        "Linus Tech Tips": false,
        "Channel Super Fun": false,
        "Floatplane Exclusive": false,
        "TechLinked": false,
        "Techquickie": false
      }
    }
  ],
  "repeatScript": "false",
  "cookie": [
  ],
  "cookies": {
  },
  "ffmpeg": true,
  "logging": true,
  "logFile": "./float.log",
  "remotePlex": false,
  "remotePlexIP": "",
  "remotePlexPort": 32400,
  "plexToken": "",
  "localPlex": false,
  "plexSection": "0",
  "plexScannerInstall": "C:/Program Files (x86)/Plex/Plex Media Server/Plex Media Scanner.exe",
  "autoFetchServer": true,
  "floatplaneServer": "https://Edge02-na.floatplaneclub.com",
  "video_res": 1080,
  "checkForNewSubscriptions": true,
}
```

I removed the cookie & cookies value, and the username, password and key (what's the key exactly by the way?) for obvious reasons.

**Comment by rob1998** [comment]
I keep thinking that it's some sort of network issue, but I can't figure out how that would be possible, everything else works. Downloading through the website works, and pinging it works as well

**Comment by rob1998** [comment]
It seems to be working more often now on the server, even though it still spits out that error and doesn't get every video. I'll be investigating more this weekend.

**Comment by Inrixia** [comment]
Yea I am lost as to why its getting the error too, must be something on floatplanes site of things. And the key is a key that is generated for downloading a video. Its valid for a period of time but for all videos. The script fetches a fresh one every start.

**Comment by rob1998** [comment]
Yeah I think so as well, gotta figure out if I can do something about it, or if I can write a nice report of it for them to fix.
Thanks for the explanation of the key 😄 
Issue can be closed for the moment I think, since I don't think we can change anything

**Comment by Inrixia** [comment]
I believe this was fixed in a previous update. If not reopen.
