### ISSUE TITLE
Day to keep videos

### ISSUE THREAD

**Issue by draco1544** [Inrixia/Floatplane-Downloader#162]
Hi ! This setting is not available anymore ?

**Comment by Inrixia** [comment]
It is, it's just not automatically populated on channels now. You just need to add the property to the channels you want with the value you want.

I might need to update the wiki to better explain this

**Comment by draco1544** [comment]
> It is, it's just not automatically populated on channels now. You just need to add the property to the channels you want with the value you want.
> 
> I might need to update the wiki to better explain this

Thanks a lot !
