### ISSUE TITLE
Wiki mistake

### ISSUE THREAD

**Issue by Fma965** [Inrixia/Floatplane-Downloader#163]
https://github.com/Inrixia/Floatplane-Downloader/blob/master/wiki/docker.md

If you want a interactive session you need to set headless to false, so initial setup should be 

```
 $ docker run -it \
    	-v [path]:/fp/db \
    	-v [path]:/fp/videos \
    	-e headless="FALSE" \
    	-e runQuickstartPrompts=true \
    	--restart unless-stopped \
        inrix/floatplane-downloader
```

NOT

```
 $ docker run -it \
    	-v [path]:/fp/db \
    	-v [path]:/fp/videos \
    	-e headless="TRUE" \
    	-e runQuickstartPrompts=true \
    	--restart unless-stopped \
        inrix/floatplane-downloader
```

**Comment by Inrixia** [comment]
Default is no headless so you can actually just remove the argument.

Feel free to open a PR to fix this, otherwise Ill eventually get to it. Thanks for noticing it

**Comment by Fma965** [comment]
Ofcourse, i just spend like 10 minutes trying to figure out why interactive wasn't working 😆

**Comment by Fma965** [comment]
It's still wrong on the master branch though, which is where most people are going to read the instructions.
