### ISSUE TITLE
Videos fail to download when parts are unavailable

### ISSUE THREAD

**Issue by mattkdoggie** [Inrixia/Floatplane-Downloader#166]
Multipart videos will not finish downloading and will stall the downloader if a part is not available for download. For example the videos bellow have one part with no downloads available.

- https://www.floatplane.com/post/Eli2hD6Dq9
- https://www.floatplane.com/post/HEpDlyrvXB

Edit: The videos above no longer have a missing part

**Comment by lifeunexpected** [comment]
im getting the same issue on a few different videos including the one you posted:
https://www.floatplane.com/post/HEpDlyrvXB

and i think the 2 latest LTT Floatplane Exlusive ones too

**Comment by Inrixia** [comment]
This should be fixed on dev now. Thanks for the reports

Please re-open if it isnt
