### ISSUE TITLE
[Feature Request] Download only specific videos (by ID or date range)

### ISSUE THREAD

**Issue by aaronjamt** [Inrixia/Floatplane-Downloader#167]
I was looking for a way to force it to download only specific videos (based on their ID) or ideally even by a range of dates. I don't want to download every single LTT FloatPlane Exclusive ever released just to have the oldest ones I haven't yet watched available locally. Is there any way this can be added? I can help implement it if you want.

**Comment by Inrixia** [comment]
Go check the settings wiki, there are several settings that will give you what you want. Though what you are describing sounds like channel filtering. 

If settings doesn't offer what you want feel free to reopen with further specifics

**Comment by Inrixia** [comment]
Speaking of release date channel filtering. This PR adds two new properties you can use to filter based on releasedate https://github.com/Inrixia/Floatplane-Downloader/pull/168

Could be relevant to what you want to do.

Note the main wiki does not show dev changes

**Comment by aaronjamt** [comment]
> Go check the settings wiki, there are several settings that will give you what you want. Though what you are describing sounds like channel filtering.
> 
> If settings doesn't offer what you want feel free to reopen with further specifics

The only setting I found that seemed like it might do what I want is `seekAndDestroy`, so I put in the IDs of the videos I wanted to download but it said it was "destroying" them. I couldn't figure out what it actually does, but it's not "download only these".
