### ISSUE TITLE
Downloads hanging, not continuing to search for new videos

### ISSUE THREAD

**Issue by rocketeer55** [Inrixia/Floatplane-Downloader#169]
Hi all,

I am having an issue where my Floatplane-Downloader container is hanging, and not completing the download process. I was originally having an issue where my container would crash (see https://github.com/Inrixia/Floatplane-Downloader/issues/153), but I added --restart=unless-stopped to my unraid container config, so at least my container stays running now. However, the container will stop grabbing new videos shortly after it has been spun up. Logs below:

```> Fetching user subscriptions... Done!


> Fetching latest videos from [LTT Supporter Plus]... Fetched 15 videos! Skipped 0.
> Processing 16 videos...
TechLinked - TL: Microsoft vs Nvidia, NYPD robot dogs, Reddit AI scraping + more! - Downloading...
LMG Livestream VODs - April 19, 2023 @ 22:31 – Random Stream for Review of Geminos - Downloading...
Linus Tech Tips - Nintendo’s Lawyers are Ready This Time - Nintendo NDev Wii Dev Kit - Downloading...
LMG Livestream VODs - April 18, 2023 @ 21:41 – I Resisted Building This… It was Futile - Downloading...
ShortCircuit - SC: This. Is. FANTASTIC! - Hyundai IONIQ 6 - Downloading...
FP Exclusive - FP Exclusive: Writers & Labs Chair Building Vlog - Downloading...
Techquickie - TQ: Why Windows Still Has The Old Control Panel - Downloading...
TechLinked - TL: Ads in Win11, RTX 4060 Ti leak, iPhone bugs + more! - Downloading...
ShortCircuit - SC: Want better Cooling? Get this. - ASUS RTX 4070 GPUs (SPONSORED) - Downloading...
Linus Tech Tips - YouTube Made Me Review This Budget GPU - GT 1030 - Downloading...
Linus Tech Tips - This is Pure False Advertising - HP Gaming Keyboard 550 - Downloading...
ShortCircuit - SC: I'd rather have NOTHING! - Unihertz Luna - Downloading...
The WAN Show - Livestream VOD – April 15, 2023 @ 02:18 – I Give Up -  April 14, 2023 - Downloading...
TechLinked - TL: AutoGPT, Windows handheld mode, WD hack + more! - Downloading...
Mac Address - MA: Living with ONLY the Apple Watch for a Week - Downloading...
FP Exclusive - FP Exclusive: Working for LMG Full Interviews (Pt. 1) - Downloading...
FP Exclusive - FP Exclusive: Working for LMG Full Interviews (Pt. 1) - ERR: Response code 429 (Too Many Requests) - Retrying in 0s [0/5]
FP Exclusive - FP Exclusive: Working for LMG Full Interviews (Pt. 1) - Downloading...
```

This final line in the logs was posted probably 12-14 hours ago. No additional lines in the logs have been created since then. The container is still running. Normally I would expect to see the `Checking for new videos in 5 minutes` message show up. The 'FP Exclusive: Working for LMG Full Interviews (Pt. 1)' video has not completed downloading (the download is also not progressing based on watching the file size). Seems to me like some error was thrown that isn't being handled properly in the downloading process.

Currently my solution to this bug is a script that restarts the container every 24 hours... however I noticed that by doing this, this container will process and 'download' all the last 15 episodes even if they have already been successfully downloaded and imported into my Plex library. I'm guessing this is because the whole download process is never completing and these episodes are not being marked as downloaded in this container's db, even though they show in Plex?

**Comment by mattkdoggie** [comment]
Have you tried the dev build? You can try stopping the container, deleting the .partial files and restart.

**Comment by Inrixia** [comment]
Yea please try the dev build and see if it fixes your issues

**Comment by rocketeer55** [comment]
Thanks guys, looks like the dev build is working! Any idea when these changes will be rolled into :latest ?

**Comment by Inrixia** [comment]
Usually takes a while before I do another release but I may do one soon.

**Comment by Inrixia** [comment]
Dev has been merged into master now so all fixes are live.
