### ISSUE TITLE
Latest WAN Show bouncing between folders

### ISSUE THREAD

**Issue by rocketeer55** [Inrixia/Floatplane-Downloader#173]
The latest WAN Show episode downloaded successfully, but now every 5 minutes it is being moved automatically from 'The WAN Show' folder to the 'Linux Tech Tips' folder or vice versa. I am running the most recent version of the 'dev' branch build. When I pause/stop the Floatplane-Downloader container, the file stops moving between the two folders.

There is not much relevant in the logs, but there was one 'no such file' error (shown below):
```[12:49:32 AM] Checking for new videos in 5 minutes...
April 29, 2023 @ 24:44 – Should We Move To America? - April 28, 2023 - Waiting on delivery cdn...
April 29, 2023 @ 24:44 – Should We Move To America? - April 28, 2023 - Waiting on delivery cdn...
[12:54:34 AM] Checking for new videos in 5 minutes...
April 29, 2023 @ 24:44 – Should We Move To America? - April 28, 2023 - Muxing ffmpeg metadata...
April 29, 2023 @ 24:44 – Should We Move To America? - April 28, 2023 - Muxing ffmpeg metadata...
April 29, 2023 @ 24:44 – Should We Move To America? - April 28, 2023 - ERR: ENOENT: no such file or directory, unlink './videos/Linus Tech Tips/Linus Tech Tips - S2023E0429005100 - April 29, 2023 @ 2444 – Should We Move To America April 28, 2023.partial' - Retrying in 0s [0/5]
[12:59:36 AM] Checking for new videos in 5 minutes...
```
No further log messages related to this file have shown in the logs but the video continues to be moved between folders every 5 minutes. No other files (that I can tell) are being moved in such a fashion.

**Comment by Inrixia** [comment]
Hmm weird. This should only be happening if it's it's channel is changing on floatplanes end. Ig I'll have to look into why it's constantly changing. Ty

**Comment by Inrixia** [comment]
This should be fixed please let me know if it is thanks.

**Comment by rocketeer55** [comment]
Seems to be fixed! Thank you
