### ISSUE TITLE
[Feature suggestion] Ffmpeg

### ISSUE THREAD

**Issue by TakenMC** [Inrixia/Floatplane-Downloader#178]
Could you add the ability to use your own ffmpeg binary or system one in the config file so it doesn't keep generating new ones in the config dir.

**Comment by Inrixia** [comment]
What is the point of this?

**Comment by TakenMC** [comment]
Just so it doesn't keep generating new ones in the specific location and if no binary is selected then like it would auto download like usual

**Comment by Inrixia** [comment]
It shouldn't be generating a new ffmpeg if it already exists. Are you getting that behavior?

**Comment by TakenMC** [comment]
It's not what I was saying, is that it generates a new one every time I reset the db folder

**Comment by Inrixia** [comment]
Right that's the intended behavior. Why is that a bad thing?

**Comment by TakenMC** [comment]
Not necessarily but it would be great to have it used the system binary

**Comment by Inrixia** [comment]
What is the actual benifit of it doing so? If you want to use a custom binary you can just replace the existing one.

**Comment by TakenMC** [comment]
I mean I can't see a tangible benefit, it would be nice if you could have a different location for it.

**Comment by Inrixia** [comment]
Right, well in that case I really don't see a need to add extra complexity to how ffmpeg pathing is handled.

If you do think of something feel free to reopen this though.
