### ISSUE TITLE
Feature request: let me chose between only captioned or non-captioned videos

### ISSUE THREAD

**Issue by traktuner** [Inrixia/Floatplane-Downloader#179]
Hello,
is it possible to integrate a setting for videos where a captioned and non-captioned version is available, to download either both, or one of them? I think it's a waste of disk space and I would prefer to only keep the non-captioned videos.
Thank you!

**Comment by Inrixia** [comment]
I can look into it, its something I considered previously but as there is no actual property on a video which indicates if its captioned so it may not be possible unfortunately

**Comment by traktuner** [comment]
"After" the video got downloadet there are the "captioned" and "uncaptioned" versions of that video -> It would not save bandwith (I don't care) but maybe automatically delete the video I don't like afterwards? 😅

**Comment by Inrixia** [comment]
Yea looking over the fp exclusive videos the title of the attachments is inconsistent "captioned" vs "captions" etc and both captioned and non captioned attachments have the word caption in them so it wouldnt be simple to try and determine which is which. 

If floatplane adds tags etc to the videos to identify which is which or uses a more consistent naming scheme then this would be possible but I doubt they will. Similar to how things were before the new sub channels. 

If its a major issue a lot of people want then I could work on something to try and separate them but it would easily be broken by the floatplane team deciding to change the naming scheme and could have false positives sadly.

**Comment by juchong** [comment]
@Inrixia maybe a bit scuffed suggestion, but what if you only kept the "first" file returned by the API. I don't think most people here care whether they're downloading the captioned or uncaptioned file.

**Comment by Inrixia** [comment]
@juchong Except there are many posts which have multiple videos on them as attachments so that wouldnt work.

Currently if you want to filter it you can setup a channel filter to try do so based on the contents of the title

**Comment by juchong** [comment]
> @juchong Except there are many posts which have multiple videos on them as attachments so that wouldnt work.
> 
> Currently if you want to filter it you can setup a channel filter to try do so based on the contents of the title

If that's the case, what if support was added for an external "mapping" file? I don't really see FP changing legacy media at this point, and I'm sure there's someone in the community that would be willing to create a detailed map.

**Comment by Inrixia** [comment]
The issue is that LTT can and has changed the title format before, it can be inconsistent.

Regarding the use case, it can be used for all kinds of stuff but most people use it to have a mirror of videos in plex so they can watch offline or if they have a slow connection have it download so they can watch without buffering etc.

Regarding a mapping of some kind, there is already support for making rules to exclude videos if for example their title contains "captioned" etc, so using that is something you could do yourself right now if you wanted to using subchannels (which are detailed on the wiki)
