### ISSUE TITLE
Ignore specific videos by name or ID

### ISSUE THREAD

**Issue by traktuner** [Inrixia/Floatplane-Downloader#180]
Hello,
is it possible to somehow ignore specific videos to be downloaded by name or ID (forever)?
For instance - my usecase would be that certain videos are broken (already reported, and still not fixed), which result in floatplane-downloader throwing an error because it can't be muxed. And most of the time the docker container get's stuck and I have to restart it.
That would solve this problem.
Thank you!

**Comment by Inrixia** [comment]
Could you open a issue regarding the broken videos? I can probably do something to handle those.

As for filtering videos you can use the channel filtering to specify videos to ignore, if you need help figuring it out you can check the wiki and feel free to ask for help here or on discord

**Comment by traktuner** [comment]
Thank you very much!

The video which always pops up is this one (captioned version):
https://www.floatplane.com/post/OFHLAvgQmZ

**Comment by Inrixia** [comment]
Just did a test manually targeting that video and it downloads fine using the dev version. Sounds like it might be a issue on your end, perhaps try deleting all the files related to it and redownloading it. Will close this for now, lemme know if you needed any extra help with filtering captioned videos

**Comment by traktuner** [comment]
Hello,
no, definetely nothing on my end.
Downloaded via web:
Captions - FPX Metal 3D Printer.mp4 (4K).mp4 - 442,2MB

No Captions - FPX Metal 3D Printer.mp4 (4K).mp4 - 1,28GB

I can't even open the captions-version with VLC (0:00), so the video is corrupt. If it's downloading for you - fine - but not for me. Maybe a CF caching issue. The docker container constantly hangs on this one, trying to mux the video with ffmpeg but can't since it's broken.

**Comment by Inrixia** [comment]
Can you try a clean install using the latest version and see if this still happens?

**Comment by traktuner** [comment]
./videos/FP Exclusive/FP Exclusive - S2023E0412045301 - We Got a Metal 3D Printer! Captions.partial: Invalid data found when processing input
ffmpeg version 4.4.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7846e40] moov atom not found
./videos/FP Exclusive/FP Exclusive - S2023E0412045301 - We Got a Metal 3D Printer! Captions.partial: Invalid data found when processing input
 Max Retries! [5/5]
 
 this is the output from the current v5.9.0
I already reported toe issue to floatplane support, maybe they'll fix it..

**Comment by Inrixia** [comment]
Are you testing on arm? Could you try test on windows/Linux and lemme know if you get the same behavior?

**Comment by Inrixia** [comment]
To be fair when I tested I didn't use the 4k version so perhaps it's a issue with that file specifically.

If you wanna manually fix it you can try renaming the partial file to mkv. It just won't have the Metadata in it which isn't strictly required but plex won't automatically get the video title

**Comment by traktuner** [comment]
Thank you! I renamed it and now it's OK for me :)
