### ISSUE TITLE
[Feature] Add rate bandwidth rate limiter

### ISSUE THREAD

**Issue by inzsome** [Inrixia/Floatplane-Downloader#182]
It would be great if we could throttle our downloads via the settings. Say, I don't want to dedicate my full bandwidth for video downloads to avoid spikes, I would just set the throttle to a desired rate via the settings.

I'm not an expert on Node, but this might be going in the right direction: https://github.com/tjgq/node-stream-throttle

**Comment by Inrixia** [comment]
This should be very easy to implement using the library you provided thanks.

**Comment by Inrixia** [comment]
Added in latest dev. Reopen if there are issues. Thanks for the great feature idea!
