### ISSUE TITLE
Response code 403 (Forbidden)

### ISSUE THREAD

**Issue by inzsome** [Inrixia/Floatplane-Downloader#183]
Trying to login results in the error message
```
Looks like the login detail's didn't work, Please try again... RequestError: Response code 403 (Forbidden)
```

I can login with the same credentials via the website, so they are 100% correct.

What could be the issue here?

**Comment by Inrixia** [comment]
Can you try login on the site from the same IP as the container and see if that fixes it. Afik there are some new cloudflare rules that may be causing issues.

**Comment by inzsome** [comment]
I guess this was a false alarm on my part. I just updated to the latest version and it seems to work as usual now.

Sorry to bother you and thanks for the quick reply!

**Comment by Maelstrom96** [comment]
Foe anyone wondering in the future, we have blocked version 5.9.0, which is why you were getting a 403 error there. Updating to the latest version should fix this.
