### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Nekotje** [Inrixia/Floatplane-Downloader#184]
When i start the container i get now
 ERR: spawn ./db/ffmpeg EACCES - Retrying in 4s [4/5] on all downloads.

**Comment by Inrixia** [comment]
This is a permissions issue. Make sure that the container has permission to execute the ffmpeg binary at that oath.

**Comment by Nekotje** [comment]
been using UMASK 000 for all my dockers and and also this one its been running fine for a long time but since begin last month i noticed it does not convert it anymore. maybe a bit sooner have to check other directories.  i also changed it to 022 and still the same problem. So i have no idea where to look then.

**Comment by Inrixia** [comment]
Yea unraid can be weird with permissions and I don't strictly maintain the unraid template, though afik it should just internally use the docker image which I do maintain so all should work.

Sounds like you got it working though so Ill close this for now. Please re-open it if its still a problem.
