### ISSUE TITLE
ENAMETOOLONG - TechLinked

### ISSUE THREAD

**Issue by TakVap** [Inrixia/Floatplane-Downloader#186]
The latest TechLinked episode / Christmas special seems to trigger the name too long issue again, this was seemingly previously patched for a WAN Show issue but has reoccured here.

The 2023 TechLinked Christmas Sp: ████▌  99% | ERR: spawn ENAMETOOLONG Max Retries

Using version 5.10.2

![image](https://github.com/Inrixia/Floatplane-Downloader/assets/4213609/3f6907e4-cc17-4978-9c07-04fd60872758)

**Comment by Inrixia** [comment]
Fix pushed to dev. Please let me know how it goes and close if fixed

**Comment by TakVap** [comment]
Unfortunately the same behavior, is it perhaps tied to the nfo size? As the filename length isn't particularly long compared to other episodes. The nfo is 3x the size of any other video released 'this year' under the same channel due to being a round-up episode with many sources.

![image](https://github.com/Inrixia/Floatplane-Downloader/assets/4213609/c10ac0a3-e4d5-460c-92ce-49d1cbdbe7be)

**Comment by TakVap** [comment]
Absolutely no rush, glad it makes sense  - have a great Christmas break 😄 🎄
