### ISSUE TITLE
Downloading to an external HDD or SSD (macOS)

### ISSUE THREAD

**Issue by ThePlayingGoblin** [Inrixia/Floatplane-Downloader#193]
Hello and I tried to edit the config.json to do "Volumes/Music Backs/Floatplane/%channelTitle%/%channelTitle% - S%year%E%month%%day%%hour%%minute%%second% - %videoTitle%" for file path formatting, but it still downloads to the same drive. How do I change this behaviour?

**Comment by Inrixia** [comment]
`Volumes/` will go to the current working directory of the downloader and create a folder `Volumes`, you need to have a complete path, maybe `/Volumes` if you are on linux

**Comment by ThePlayingGoblin** [comment]
> `Volumes/` will go to the current working directory of the downloader and create a folder `Volumes`, you need to have a complete path, maybe `/Volumes` if you are on linux

Hello,

I managed to fix this. I might as well mention it here instead of making a new issue, 

Only 21 of the latest videos were able to download and I have no success downloading anything else.

[settings.json](https://github.com/Inrixia/Floatplane-Downloader/files/15050937/settings.json)

I want to download every single FP exclusive, but I don't know how to do this. I tried marking true to skipping the other channels but nothing works.

**Comment by ThePlayingGoblin** [comment]
When it launches, it just tells me:
Searching for new videos in LTT Supporter
Checking for new videos in 5 minutes...

**Comment by Inrixia** [comment]
You would probably benefit from jumping on the discord if you want faster responses.

And have you changed the `videosToSearch` setting? The wiki for all the settings can be found here: https://github.com/Inrixia/Floatplane-Downloader/blob/master/wiki/settings.md

**Comment by ThePlayingGoblin** [comment]
> You would probably benefit from jumping on the discord if you want faster responses.
> 
> And have you changed the `videosToSearch` setting? The wiki for all the settings can be found here: https://github.com/Inrixia/Floatplane-Downloader/blob/master/wiki/settings.md

Ok, thanks for this. If I need further help, I'll reach out to you there.
