### ISSUE TITLE
[Feature Suggestion] Randomize default "check for new content" interval

### ISSUE THREAD

**Issue by britto89** [Inrixia/Floatplane-Downloader#194]
Since we don't need to have the video as soon as it's posted (if we wanted to watch straight away we'd click the notification) the default option should be to check for new videos some random interval between 5-60min. This would ensure we don't all hit the servers at the same time.

**Comment by Inrixia** [comment]
As all downloaders don't start immediately their check interval is already randomly distributed over 5 minutes. 

Something that can be observed in this graph here. 

![Screenshot_20240411_154200_Chrome](https://github.com/Inrixia/Floatplane-Downloader/assets/6373693/89788a41-fb79-43d5-ab9a-71f777132610)
