### ISSUE TITLE
Version checker is notifying an update is available when on latest pull from dev branch. (docker-compose)

### ISSUE THREAD

**Issue by tewan** [Inrixia/Floatplane-Downloader#202]
In the logs when running headless this is logged:

> Node.js v21.7.2
> (node:1) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:1) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> [5/2/2024, 12:17:44 AM] There is a minor update available! 5.12.2 > 5.13.0.
> Head to https://github.com/Inrixia/Floatplane-Downloader/releases to update!
> 
> [5/2/2024, 12:17:45 AM] Initalized! Running version 5.12.2 instance 629f88f9b3edbb70e085184d
> [5/2/2024, 12:17:45 AM] [5/2/2024, 12:17:45 AM] Checking for new videos in 5 minutes...

**Comment by Inrixia** [comment]
Cant reproduce lmk if its still happening
