### ISSUE TITLE
[Feature request] H265 and AV1 support 

### ISSUE THREAD

**Issue by Frooodle** [Inrixia/Floatplane-Downloader#209]
H265 and AV1 support (mostly h265)

**Comment by Inrixia** [comment]
Do you know if the new formats are available on floatplane now?

I'll definitely take a look.

**Comment by Frooodle** [comment]
I dont believe so but with ffmpeg you should be able to convert on the fly as a very slow option

**Comment by Inrixia** [comment]
If the site isn't supporting the new formats then there's nothing to do.

If you want to convert after the fact you can either use the postProcessingCommand setting or a tool that automatically encodes like tdarr.

I'll close this for now but if floatplane adds support for those codes do let me know.

Feel free to continue this discussion here regardless of the issue status.
