### ISSUE TITLE
Videos Forbidden

### ISSUE THREAD

**Issue by Mochaka** [Inrixia/Floatplane-Downloader#21]
I'm trying to look into this issue, maybe you might know what's up.

Half the videos that are downloading end up being 72bytes with html contents, but it only happens on random videos. If i re-run it, it works fine, but it ends up duplicating videos with different episode numbers.

Contents:
<html><head><title>Forbidden</title></head><body>Forbidden</body></html>

Thanks

**Comment by Inrixia** [comment]
There was a similar issue that came up but I don't know if it ever got resolved as the user didn't get back to me. What should be happening to cause this is the floatplane API returning <title>Forbidden</title>Forbidden when float tries to download a video. Are you running with default settings? And where are you located?

**Comment by Mochaka** [comment]
Yeah it's quite strange.  Need to somehow intercept the error and retry.

I'm from Australia, but using edge 1 NA to download from. 

Upon re-running the script it works again, but creates duplicate episodes.

**Comment by Inrixia** [comment]
Easy way to do that would be to add some code in 
```javascript 
}).on('end', function () { // When done downloading
``` 
in the downloadVideo function or in
```javascript
.on('finish', function () {
```
to check if the finished download is a string, and then handle the error from there.

That said so far few people have encountered it which is weird, are you sure you are only running one instance of the script at a time? Also most if not all edges aside from NA have downloads disabled so don't try use others if you are. The autofetch function for edges will determine to best one to use automatically.

**Comment by Inrixia** [comment]
Just checked back in with that user, as far as we know the issue was having multiple instances of the script running at the same time. Or multiple requests being sent to floatplane for the same video.

**Comment by peskdale** [comment]
I'm having this issue quite regularly at the moment. Only running one instance of the script. Located in the UK, using autofetch for server. Deleting the bad files gets the script to redownload successfully.

I'll try switching to edge02-na as default and see if it improves things. However, some sort of catch for this would still be useful.

I would propose that instead of checking for a string, just check the final video size:
```
                // Tick the progress bar to display the totalMB/totalMB
                bar.tick({'title': displayTitle, 'stats': `${(total/1024000).toFixed(0)}/${(total/1024000).toFixed(0)}MB`})
                bar.terminate();
                if (videos[video.guid].size < 10000) {
                        delete videos[videoID]; // If the downloaded video is less than 10kb its failed. Remove it and reattempt next time the script runs.
                        fLog('Download > An error occoured for "'+video.title+'": Downloaded file too small!');
                        console.log(`An error occurred: Downloaded file too small!`);
                } else {
                        videos[video.guid].partial = false;
                        videos[video.guid].saved = true;
                        queueCount -= 1 // Reduce queueCount and liveCount by 1
                        liveCount -= 1
                }
                saveVideoData();
```
This is just an adaptation of the existing code in checkExistingVideos, and allows for other download issues to be caught outside of forbidden access.

I haven't tested the above as of yet, but hopefully this is sane.
