### ISSUE TITLE
No binary for macOS in latest release (5.15.0)

### ISSUE THREAD

**Issue by VioletLovesJasmine** [Inrixia/Floatplane-Downloader#212]
Is this a mistake or you plan to no longer publish binaries for macOS?

I couldn't see this change mentioned  anywhere.

Thank you :)

**Comment by Inrixia** [comment]
Yea this is just me not having added support for it to the new builds due to lack of Testers.

I'll add support for it in a upcoming dev release that should include some other fixes and get you to test it.

Thanks for letting me know ❤️

**Comment by VioletLovesJasmine** [comment]
awesome, yeah happy to test stuff for you any time, just dm me. Love to be of some help on this project :)

**Comment by Inrixia** [comment]
If you are on the discord gimme a ping. Otherwise I'll let you know here when it's ready.

Probably will be either late today or sometime this week depending on when I get time. But most likely later today in ~6hrs

**Comment by Inrixia** [comment]
As of https://github.com/Inrixia/Floatplane-Downloader/commit/fd0d96764bea4c6d8a7a5adaf83b09de24864210 there is now a dev build artifact for macOS. 

Please let me know if it works <3
