### ISSUE TITLE
Only download from specific subchannel with env variable. EX: only download FP exclusives

### ISSUE THREAD

**Issue by pandaboy6621** [Inrixia/Floatplane-Downloader#213]
I would like the option to only include a specific subchannel to download that is defined in env variables.

**Comment by Inrixia** [comment]
Use the advanced env config to define your channel skip settings.

https://github.com/Inrixia/Floatplane-Downloader/blob/master/wiki/advenv.md

Let me know if you run into issues getting it working, discord might be easier to discuss it than here though.
