### ISSUE TITLE
Error calling updatetast(): Task does not exist

### ISSUE THREAD

**Issue by ForeheadFox** [Inrixia/Floatplane-Downloader#215]
Odd error that pops up.
![image](https://github.com/user-attachments/assets/7ded5c6f-a5bc-45a3-b213-0be73e1a0875)
--
![image](https://github.com/user-attachments/assets/5d123a8f-2589-4847-989b-b5e962409130)
yep, here it is.

**Comment by Inrixia** [comment]
There might be a edge case on this. Let me know if you notice anything like this cropping up again thx
