### ISSUE TITLE
Getting ERR: ffmpeg:  Metadata:    major_brand     : isom    minor_version   : 512    compatible_brands:  on some videos

### ISSUE THREAD

**Issue by zd3wz** [Inrixia/Floatplane-Downloader#217]
Some videos are producing an error with ffmpeg when attempting to mux. 

```
 Extras - AMD Ultimate Tech Upgra:                                            0% | ERR: ffmpeg:  Metadata:    major_brand     : isom    minor_version   : 512    compatible_brands: 
    Extras - AMD Ultimate Tech Upgra:                                            0% | ERR: ffmpeg:  Metadata:    major_brand     : isom    minor_version   : 512    compatible_brands: 
Extras - AMD Ultimate Tech Upgra [2]:                                            0% | ERR: ffmpeg:  Metadata:    major_brand     : isom    minor_version   : 512    compatible_brands: 
    Extras - AMD Upgrade Colin De Gr:                                            0% | ERR: ffmpeg:  Metadata:    major_brand     : isom    minor_version   : 512    compatible_brands: 
    Cut Content - Scrapyard War Crew:                                            0% | ERR: ffmpeg:  Metadata:    major_brand     : isom    minor_version   : 512    compatible_brands: 
```

Currently the videos it is happening to: 
https://www.floatplane.com/post/9L7HJNEH4a
https://www.floatplane.com/post/obFqakHwE1
https://www.floatplane.com/post/gGKhm6AU4A

I have deleted the .ffmeta file and started the process over, occasionally it will resolve the issue and process properly. 
Deleting the .partial and .ffmeta files and starting over resolves the issue intermittently.

**Comment by Inrixia** [comment]
This might fix it. Can you please pull the latest dev and let me know if it does thanks.

https://github.com/Inrixia/Floatplane-Downloader/commit/e36a23ca6673982c4c649c197db96915c7422f57

**Comment by Inrixia** [comment]
Going to close this for now. Please re-open it if you encounter it again thx.
