### ISSUE TITLE
Unable to download more than 1 video using seekAndDestroy setting

### ISSUE THREAD

**Issue by BijnensMatti** [Inrixia/Floatplane-Downloader#220]
When using the `seekAndDestroy` option in the settings there seems to be an issue. Only 1 of the videos is actually downloaded, the other items are just deleted.

For example using following settings: 
```json
   "floatplane": {
        "videosToSearch": 5,
        "videoResolution": "1080",
        "waitForNewVideos": true,
        "seekAndDestroy": [
            "DM5gUhzHBH",
            "7EJkbVQTEN"
        ]
    },
```

The output of the script was (only downloaded 1 of the specified videos but deleted both from the `seekAndDestroy` list): 

![image](https://github.com/user-attachments/assets/05defbb2-b134-4baf-80ee-9e7937daccaf)

Attached you can find both my settings and attachment file from **before** and **after** running the script.
[pre_attachments.json](https://github.com/user-attachments/files/17554139/pre_attachments.json)
[pre_settings.json](https://github.com/user-attachments/files/17554140/pre_settings.json)
[post_attachments.json](https://github.com/user-attachments/files/17554141/post_attachments.json)
[post_settings.json](https://github.com/user-attachments/files/17554143/post_settings.json)

**Comment by Inrixia** [comment]
Thanks for letting me know, Ill look into this when I get time <3

**Comment by Inrixia** [comment]
Fixed in https://github.com/Inrixia/Floatplane-Downloader/commit/0030d99e465052df8a07d28ef4ac627eb6714670 seekAndDestroy was consuming the subscriptions asyncIterable which meant that after the first guid no other videos could be queued.

**Comment by BijnensMatti** [comment]
Awesome, thank you for the quick fix! 

Any idea when a new release will be published containing this fix?

**Comment by Inrixia** [comment]
Changes on dev are built and released when pushed so if using containers pull dev image, or download the latest release binary and you can try it now.
