### ISSUE TITLE
Feature Request: Ability to minimize to system tray + QoL for this change

### ISSUE THREAD

**Issue by weeurey** [Inrixia/Floatplane-Downloader#224]
An ability to minimise to the system tray to reduce clutter would be a massive help. Also maybe notifications when a new "episode" is downloaded and some form of status when hovering over (similar to qBittorent for example)

**Comment by Inrixia** [comment]
Why can't you minimize to system tray?

And status when hovering over what?

**Comment by weeurey** [comment]
> Why can't you minimize to system tray?
> 
> And status when hovering over what?

I'm not too sure what isn't coming across... The system tray is all the little icons beside the clock. It would be nice if the program could be minimized to that tray, when you hover over there icon in that tray a toast would pop up with a message "waiting for new videos" or "downloading xxxxx xx% completed" ect

**Comment by Inrixia** [comment]
Ah right. systray support in node is rudimentary at best and requires dependencies that likely would not work well with packing builds.

So unfortunately I'm going to close this as not planned as the features you want aren't really supported in node.

If you still wanted notifications desktop notifications could work, Id need to check and see how platform agnostic options are. Feel free to open a new issue for that if its something you would want and I can look into it.
