### ISSUE TITLE
downloads not working

### ISSUE THREAD

**Issue by ehtical32** [Inrixia/Floatplane-Downloader#228]
when  any of videos gets to 100% it goes red saying "err the operation would yield an inc" is this an issue on my end I put the exact same settings as on the GitHub page so I don't understand why its coming up with an error

**Comment by Inrixia** [comment]
Are you on the dev version? Fairly sure this is a ffmpeg error that has been resolved if you switch to dev

**Comment by ehtical32** [comment]
> Are you on the dev version? Fairly sure this is a ffmpeg error that has been resolved if you switch to dev

how would i switch to dev version?

**Comment by Inrixia** [comment]
If you are on docker just set your tag to dev, or grab the latest dev release under releases. Afik all the guides should point you to using the dev version

**Comment by Inrixia** [comment]
Closing as I presume this is resolved. Please comment if not thanks
