### ISSUE TITLE
Script not finding existing episodes

### ISSUE THREAD

**Issue by Mochaka** [Inrixia/Floatplane-Downloader#24]
With my settings, the glob command is returning 0 episodes found. 

I think it's because i have season folders enabled, so the glob command needs to be changed slightly, i have it set to:

```
glob.sync(`${settings.videoFolder}/${channel}/*/*.mp4`).length
```

**Comment by Inrixia** [comment]
Ill check and see about fixing this.

**Comment by Inrixia** [comment]
To fix it with support for the other formats too you have to use:
```javascript
glob.sync(`${settings.videoFolder}/${channel}/**/*.mp4`)
```

Itl get released with the next update.
