### ISSUE TITLE
Plex cant determine correct name

### ISSUE THREAD

**Issue by Buggitt** [Inrixia/Floatplane-Downloader#25]
I was wondering if it'd be possible to have the script also modify the mp4 title tag (not just the file name) as I think I've tried everything to try and get plex to recognize the names and it can't figure it out. They continue to be "Episode #" rather than the actual titles. 
![image](https://user-images.githubusercontent.com/7709438/58554794-c29ea880-81cc-11e9-89fd-eda3b442506b.png)

**Comment by Inrixia** [comment]
It already does this with ffmpeg. If you arent getting titles then something is wrong with your ffmpeg install or you have ffmpeg disabled.

**Comment by Buggitt** [comment]
That was the issue, didn't have ffmpeg installed.
Thanks!
