### ISSUE TITLE
Unable to sort videos to correct subchannel

### ISSUE THREAD

**Issue by MichaelFay** [Inrixia/Floatplane-Downloader#26]
All the videos are being sorted as LTT Supporter (OG)

**Comment by MichaelFay** [comment]
the following needs to be added to line 575 of float.js

|| subscription.plan.title == 'LTT Supporter (OG)'

**Comment by Inrixia** [comment]
Known issue since the change of the OG sub name. I'll be fixing it in the next update which is planned to hopefully happen within the next few days.

**Comment by Inrixia** [comment]
Fixed in v4.6.3
