### ISSUE TITLE
LTT Subchannels broken

### ISSUE THREAD

**Issue by Inrixia** [Inrixia/Floatplane-Downloader#27]
A floatplane change has broken subchannels. Need to modify matching to fix.

**Comment by NigelVanHattum** [comment]
Just to be sure: I've got a "LTT Supporter (OG)" subscription. It's not creating the subfolders, is this the mentioned bug?

**Comment by Inrixia** [comment]
Yes though this should be fixed in the current version with the latest push. So if you haven't yet try installing the current version again. Or using the float.js from the latest push (https://raw.githubusercontent.com/Inrixia/Floatplane-Downloader/58dbdae1261f01f87468642e02a43e3bbc43ebe1/float.js)
