### ISSUE TITLE
Issue with WAN show naming and all episode numbering

### ISSUE THREAD

**Issue by Fma965** [Inrixia/Floatplane-Downloader#28]
![image](https://user-images.githubusercontent.com/1707290/67167232-52690d00-f38f-11e9-9846-9c7bf521a02e.png)
surely this isn't right?

**Comment by Fma965** [comment]
infact it seems like all your episode numbers are screwy...

the latest episode on floatplane at the current time is 
LTT Supporter (OG) - S01E130 - Round up $50-$75 Gaming Keyboards

but despite this being episode S01E130 i have loads of episodes higher...
LTT Supporter (OG) - S01E820 - Ultimate PC AND Console Gaming Battlestation
LTT Supporter (OG) - S01E819 - Overclocking a 56-Core Server - Is there ANY point

etc, any ideas whats wrong?

**Comment by NigelVanHattum** [comment]
WAN show episodes are numbered different that the floatplane videos to start.

What version of ffmpeg are you running?

**Comment by Fma965** [comment]
your first point is not relevant, i never said they were named the same, plex picks all those different wan shows up as 1 "episode" so something is clearly wrong there.

ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers

**Comment by Inrixia** [comment]
WAN support for youtube has been removed for now since they are releasing Livestream VOD's directly to floatplane.
This issue should no longer be relevant
