### ISSUE TITLE
ReferenceError: Invalid left-hand side in assignment

### ISSUE THREAD

**Issue by gergy008** [Inrixia/Floatplane-Downloader#3]
Hello,

I'm new to Node.js, when I run this script I'm getting this error, and the script doesn't appear to be adding videos into Plex. I cannot identify any processes running on my machine that indicates that this script is running and would automatically download and add videos.

Steps to reproduce:
Run `Floatplane.bat`

Output:
```
C:\WINDOWS\system32>node D:\Users\Steven.ste-gaming-pc\Desktop\plllpt\float.js
D:\Users\Steven.ste-gaming-pc\Desktop\plllpt\node_modules\pad\lib\index.js:13
    [length, text] = [text, length];
    ^

ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Users\Steven.ste-gaming-pc\Desktop\plllpt\float.js:13:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

Breakdown of my installation process:
Downloaded `Install.zip`, `Update.zip` and `Release 3.6.2.zip` from [Floatplane-Downloader Latest Release](https://github.com/Inrixia/Floatplane-Downloader/releases)
Extracted all into a single folder
Run `Install.bat`
Encountered error: `cannot find module 'fs-extra'`
Run `npm install -D grunt-cache-bust` and `npm install -D fs-extra`
Rerun `Install.bat`
Installation completes without error
Edit `Floatplane.bat` and added line:
`"C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Scanner.exe" --scan --refresh --force --section xx`
Replaced 'xx' with correct section number from the `"C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Scanner.exe" --list` command
Run `Floatplane.bat`

**Comment by Inrixia** [comment]
There appears to have been a issue with github accepting a new install.zip I pushed out while I was on holiday (Likely due to me pushing to git differently due to me being on my laptop). I have update the install.zip so if you could download only that, unzip it and run it and then tell me if everything is working for you then it should hopefully fix it.

**Comment by Inrixia** [comment]
@gergy008 Has this issue been fixed?

**Comment by gergy008** [comment]
Issue was resolved with a reinstall of Node.js and a new download of Install.zip
Not sure exactly why or how. Possible corruption or dependency issue but its working now anyways, thanks!

**Comment by Inrixia** [comment]
Good to know it was sorted :)
