### ISSUE TITLE
Error trying to download all videos

### ISSUE THREAD

**Issue by hbh7** [Inrixia/Floatplane-Downloader#31]
Hi,
I'm trying to archive all the videos. I first tried setting maxVideos to 0, but then it downloaded nothing, so then I tried -1 and still got nothing, so then tried 1000000000 and then 100000000 and am currently receiving extensive spamming of:
```
TypeError: Cannot read property 'request' of undefined
    at Request._callback (/home/hbh7/floatplanedownloader/float.js:720:23)
    at self.callback (/home/hbh7/floatplanedownloader/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.onRequestError (/home/hbh7/floatplanedownloader/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:189:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
After a while of that, it switches to spamming: 
```
No Videos Returned! Please open Floatplane.com in a browser and login...
```

It seemed to work fine when maxVideos was at 5, but they do have more than 5 videos so that won't do haha. I'll keep trying smaller numbers but this seems like a case that should be able to be handled better. 

Thanks

**Comment by Inrixia** [comment]
I would suggest against trying to use this tool to bulk download the entire floatplane library as its designed for fetching the daily content over bulk downloads. Not to mention even if everything worked perfectly for downloads larger than 100 videos the formatting for floatplane videos that allows for channel sorting etc has been changed multiple times over floatplanes lifetime meaning that episode ordering and channel splitting would break fairly quickly into the download. Sorry

**Comment by hbh7** [comment]
Hmm, so there's not a good way to "catch up" then I guess? That's too bad. I do see your point, but I feel there's got to be some way to handle it somewhat gracefully. Perhaps once I get some spare time, I'll look thru the codebase and see if I can come up with something if you or somebody else doesn't beat me to it.

**Comment by Inrixia** [comment]
> Hmm, so there's not a good way to "catch up" then I guess?

From what I have heard floatplane will be splitting the LMG channels out into their own actual "floatplane channels" sometime in the future. If this happens I am planning to rewrite a bunch of the codebase to accommodate this at which point pulling the entire floatplane library would probably be possible, presuming that the old content actually gets sorted.

Just downloading all the videos without any channel splitting would not be too hard but just is not a feature that has been added yet afik. 

Also if you disable some of the title formatting in the settings and set a value for video downloads to be queued (eg, 4) you might be able to get it to download most of them. Though the formatting may very well break.

**Comment by epicDISZ** [comment]
When I tried to do this the script ran into a bunch of weird issues (A while ago), I also think floatplanes CDNs act weird when you want to download that much video, I’d recommend just grabbing exclusives with this, and get the rest off of YouTube (although that will be with baked in ads)

**Comment by DavidSpek** [comment]
Just to pitch in. I haven’t yet tried this script, but I would be interested in grabbing all video’s. This would be very helpful for those that want to do archiving.

**Comment by Inrixia** [comment]
This is fixed with v5 which now supports bulk downloading all videos off the platform.
v5 is currently in beta on the discord if you want to try it but will be fully releasing soon.

The idea of a "official" database is cool and I may consider implementing something similar to it in the future. For now v5 uses the same numbering from first seen video but without any of the issues that plagued the original.
