### ISSUE TITLE
Error: Failure when trying to download a video and the preferred resolution doesn't exist

### ISSUE THREAD

**Issue by Hezkezl** [Inrixia/Floatplane-Downloader#36]
Had this with the recent "I'm considering retiring" video from Linus. I have my settings.json set to download 1080 videos, but the maximum resolution of that was 720. So it downloaded a partial 1kb file with the .part extension, and then errored out. As long as that 1kb file existed in my /videos/ folder, the script wouldn't even continue to checking if there were any new videos, it just kept spitting out an error about the failed 1kb.part file and refused to go on further. (Screenshot of the error uploaded to the Discord #help channel, but here's the url to it: https://cdn.discordapp.com/attachments/468977376794247199/670493998091337748/unknown.png )

Was 'fixed' by temporarily changing the .json settings to look for the 720p video and downloading that, then changing settings back to 1080 afterwards.

**Comment by Inrixia** [comment]
Will fix in the v5 rewrite that I'm doing atm. Thanks

**Comment by SlyBlueFox** [comment]
Just curious is 2160 expected to be fixed in the v5 rewrite as well? doesn't fall back to 1080p when the file is missing.

Possibly another issue with 4k is that all videos get put under LTT Supporter Plus, rather that LTT Floatplane, CSF, TQ, etc

**Comment by Inrixia** [comment]
With v5 I'll be looking into having the downloader step down quality from 2160p or whatever is specified and then handling the error if no quality works.

Though fixes like this will likely come a version after the first v5 release as once I get a working somewhat stable build I'll release that immediately for testing and feedback.

**Comment by Inrixia** [comment]
This should be added in https://github.com/Inrixia/Floatplane-Downloader/commit/564f3ce2c98297710124c8a0df000a0b7ed7eef3
