### ISSUE TITLE
Error: Cannot find module 'm3u8stream/lib/parse-time'

### ISSUE THREAD

**Issue by BlueCraziii** [Inrixia/Floatplane-Downloader#37]
When i try to run the downloader (Version 4.6.3) i get this error

Error: Cannot find module 'm3u8stream/lib/parse-time'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (E:\Download drops\4.6.3\node_modules\ytdl-core\lib\info-extras.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

> videos.json
 {
  "CGCO5sN3Fj": {
    "subChannel": "BitWit Ultra",
    "partial": false,
    "saved": true,
    "size": 294459406,
    "file": "./videos/BitWit Ultra/BitWit Ultra - S01E0 - THE BIG REVEAL! Our 7-month home renovation is COMPLETE!.mp4"
  },
  "GiMQ9rCvJP": {
    "subChannel": "BitWit Ultra",
    "partial": false,
    "saved": true,
    "size": 340707596,
    "file": "./videos/BitWit Ultra/BitWit Ultra - S01E1 - Girlfriend's gaming PC is UNACCEPTABLE!.mp4"
  },
  "2rnisq4Pv9": {
    "subChannel": "BitWit Ultra",
    "partial": false,
    "saved": true,
    "size": 142178283,
    "file": "./videos/BitWit Ultra/BitWit Ultra - S01E2 - Surprised my friend with a (really good) PC!.mp4"
  },
  "UgE76j9v56": {
    "subChannel": "BitWit Ultra",
    "partial": false,
    "saved": true,
    "size": 381499494,
    "file": "./videos/BitWit Ultra/BitWit Ultra - S01E3 - Delete this video forever (New Year's Eve vlog).mp4"
  },
  "XtzgL3GyOi": {
    "subChannel": "BitWit Ultra",
    "partial": false,
    "saved": true,
    "size": 411498953,
    "file": "./videos/BitWit Ultra/BitWit Ultra - S01E4 - My PC is idling at 100°C (for one stupid reason).mp4"
  },
  "f9Yba4FLzY": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 258502063,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E0 - We Water Cooled an SSD!!.mp4"
  },
  "hz9uGgXPqk": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 82706929,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E1 - 360Hz Gaming Monitor - I Need This NOW!! - CES 2020.mp4"
  },
  "MLpQGeNMbM": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 139529308,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E2 - ASUS DITCHES Intel.mp4"
  },
  "p97rUioQ8K": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 105443847,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E3 - A Nintendo Switch that plays PC Games.mp4"
  },
  "HkBA74SwQC": {
    "subChannel": "TechLinked",
    "partial": false,
    "saved": true,
    "size": 83006690,
    "file": "./videos/TechLinked/TechLinked - S01E0 - TL Samsung made... a PERSON! - CES 2020.mp4"
  },
  "Yi00WcvD2Q": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 46173950,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E4 - Why Can't You Install Windows on an Xbox.mp4"
  },
  "YR6LwGQtiS": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 90338545,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E5 - Who needs a car anyway - LG's New 8K OLED is BREATHTAKING.mp4"
  },
  "dP6mKk5bSj": {
    "subChannel": "TechLinked",
    "partial": false,
    "saved": true,
    "size": 103111110,
    "file": "./videos/TechLinked/TechLinked - S01E1 - TL It's the PlayStation Wagon 5 haha - CES 2020.mp4"
  },
  "A1VOp4FhgI": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 59330804,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E6 - I thought Razer's Modular concept PC was impossible.mp4"
  },
  "1jyUJywONE": {
    "subChannel": "BitWit Ultra",
    "partial": false,
    "saved": true,
    "size": 211955745,
    "file": "./videos/BitWit Ultra/BitWit Ultra - S01E5 - My 3990X dream PC might actually happen (on a $10,000 budget).mp4"
  },
  "zaWmOEGKgT": {
    "subChannel": "BitWit Ultra",
    "partial": false,
    "saved": true,
    "size": 96017837,
    "file": "./videos/BitWit Ultra/BitWit Ultra - S01E6 - Maybe LG should stand for Let's Game.  Their 2020 products look good!.mp4"
  },
  "1NYLOmHUaW": {
    "subChannel": "TechLinked",
    "partial": false,
    "saved": true,
    "size": 114775312,
    "file": "./videos/TechLinked/TechLinked - S01E2 - TL This 300 TV draws over 9000W.mp4"
  },
  "y3ffORzWjr": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 86677319,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E7 - The CRAZY laptop manufacturer you've never heard of.mp4"
  },
  "Wb9raY45dH": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 73168472,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E8 - A Laptop for Real Professionals! - Acer ConceptD 7 Ezel Pro.mp4"
  },
  "1Q344fGY4W": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 117654678,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E9 - Look at all these CES 2020 Trends! Whoa!.mp4"
  },
  "1lphIm4QyD": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 92430003,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E10 - We Tried a Surround-Screen Movie Theater! (SPONSORED).mp4"
  },
  "WLxuGXjZXg": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 95397300,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E11 - The WORST way to buy a console - Corsair - The Big O.mp4"
  },
  "NTwOwSnohl": {
    "subChannel": "TechLinked",
    "partial": false,
    "saved": true,
    "size": 96467582,
    "file": "./videos/TechLinked/TechLinked - S01E3 - TL The WEIRDEST Tech at CES 2020.mp4"
  },
  "gSAXN1Z5G1": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 94338514,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E12 - Why Can't I BUY a MicroLED TV.mp4"
  },
  "Fuff3XZzdr": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 101488403,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E13 - Why I'm Skeptical of Intel's Dedicated Graphics.mp4"
  },
  "0sL74CfKzV": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 107889794,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E14 - The biggest letdown of the week... - Samsung Neon.mp4"
  },
  "wVkageO8ss": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 92291637,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E15 - Folding laptops are here... and we have some thoughts.mp4"
  },
  "DuUXFpNTD4": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 119752221,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E16 - Are 8K TV manufacturers LYING.mp4"
  },
  "qUn1hEswEn": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 267536886,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E17 - Should you buy a $50 CPU.mp4"
  },
  "dwgYuovJVV": {
    "subChannel": "Floatplane Exclusive",
    "partial": false,
    "saved": true,
    "size": 61064882,
    "file": "./videos/Floatplane Exclusive/Floatplane Exclusive - S01E0 - Console exclusives… are DEAD.mp4"
  },
  "vc6GIyDZY2": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 373638717,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E18 - What’s the Best TV Under $400.mp4"
  },
  "M3ajdzb79B": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 523676709,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E19 - Water Cooling our RED 8K Camera (Part 2).mp4"
  },
  "yMQvKeIngR": {
    "subChannel": "BitWit Ultra",
    "partial": false,
    "saved": true,
    "size": 341318722,
    "file": "./videos/BitWit Ultra/BitWit Ultra - S01E7 - Rumors about Fry's Electronics sent us on a wild journey to find the truth.mp4"
  },
  "OgZ6Qu1ne7": {
    "subChannel": "TechLinked",
    "partial": false,
    "saved": true,
    "size": 89271861,
    "file": "./videos/TechLinked/TechLinked - S01E4 - TL Apple makes Macs LOUDER.mp4"
  },
  "ABjJ9SG4s5": {
    "subChannel": "Floatplane Exclusive",
    "partial": false,
    "saved": true,
    "size": 86674099,
    "file": "./videos/Floatplane Exclusive/Floatplane Exclusive - S01E1 - [UNCENSORED] Linus RAGING at the Teleprompter for 5 Minutes [FP EXCLUSIVE].mp4"
  },
  "zWcivFmRUY": {
    "subChannel": "BitWit Ultra",
    "partial": false,
    "saved": true,
    "size": 77676000,
    "file": "./videos/BitWit Ultra/BitWit Ultra - S01E8 - Reacting to the worst PC builds on the Internet.mp4"
  },
  "UwfpK7bCdJ": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 153417057,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E20 - Apple’s Pro Display XDR – A PC Guy’s Perspective.mp4"
  },
  "XqfOkuWXVO": {
    "subChannel": "TechLinked",
    "partial": false,
    "saved": true,
    "size": 80395977,
    "file": "./videos/TechLinked/TechLinked - S01E5 - TL I want a Gaming Chromebook.mp4"
  },
  "389pQplhVI": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 273471635,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E21 - The Best VR Headset... got BETTER!.mp4"
  },
  "2cpkPBuEQT": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 512077032,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E22 - Water Cooling our RED Camera (Part 3).mp4"
  },
  "w3veWyGdgV": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 301261912,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E23 - The Coolest Small Form Factor PC.mp4"
  },
  "wk9b3YCqAJ": {
    "subChannel": "TechLinked",
    "partial": false,
    "saved": true,
    "size": 103954633,
    "file": "./videos/TechLinked/TechLinked - S01E6 - TL iPad Pro. Better than Consoles.mp4"
  },
  "dEsFmnoto0": {
    "subChannel": "BitWit Ultra",
    "partial": false,
    "saved": true,
    "size": 68245173,
    "file": "./videos/BitWit Ultra/BitWit Ultra - S01E9 - Call 911! The RX 5600 XT just murdered the GTX 1660 Ti.mp4"
  },
  "r1qmkyiKhL": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 193989252,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E24 - It’s time to upgrade your GPU - RX 5600 XT.mp4"
  },
  "5n2vj5h9iZ": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 202896061,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E25 - FINALLY Wireless Headphones that Sound GREAT - Massdrop x THX Panda Wireless Headphones.mp4"
  },
  "WwDvrKK06C": {
    "subChannel": "TechLinked",
    "partial": false,
    "saved": true,
    "size": 95191115,
    "file": "./videos/TechLinked/TechLinked - S01E7 - TL If he texts you... DON'T OPEN IT.mp4"
  },
  "qNvvl3WDAI": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 728671259,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E26 - Carpool Critics - Parasite.mp4"
  },
  "DCBaOZ7GE6": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E27 - I've been thinking of retiring [LIVESTREAM VOD].mp4"
  },
  "Ub1cFWG40r": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 190452783,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E28 - Stop buying the MacBook Air (2013 Edition).mp4"
  },
  "JEaiyYfcGk": {
    "subChannel": "BitWit Ultra",
    "partial": false,
    "saved": true,
    "size": 335052305,
    "file": "./videos/BitWit Ultra/BitWit Ultra - S01E10 - RGB cables are evolving.mp4"
  },
  "d4Og52AeiF": {
    "subChannel": "TechLinked",
    "partial": false,
    "saved": true,
    "size": 89890350,
    "file": "./videos/TechLinked/TechLinked - S01E8 - TL Ugh, what a launch.mp4"
  },
  "3NNkTQkObZ": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 159799807,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E29 - I'm Returning my Mac Pro.mp4"
  },
  "iRVrGtkYx5": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 246587527,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E30 - We got the Kick-Proof TV from China!.mp4"
  },
  "nsIpU3tQLe": {
    "subChannel": "BitWit Ultra",
    "partial": false,
    "saved": true,
    "size": 215713045,
    "file": "./videos/BitWit Ultra/BitWit Ultra - S01E11 - Reacting to Tech YouTuber's MOST VIEWED videos.mp4"
  },
  "YmBVdL96cB": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 436451246,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E31 - Dolittle - OMG we made a mistake.mp4"
  },
  "FyuVAsMUtb": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 405035494,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E32 - Mac Pro Upgrade Adventure.mp4"
  },
  "w6VNu9xWiP": {
    "subChannel": "TechLinked",
    "partial": false,
    "saved": true,
    "size": 94348961,
    "file": "./videos/TechLinked/TechLinked - S01E9 - TL Microsoft still CARES about us😊.mp4"
  },
  "2Ff3Bqfi48": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 161927629,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E33 - Beat Saber Mixed Reality Setup.mp4"
  },
  "iCqEjcGcQ8": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 137861796,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E34 - FP Extra  Beat Saber - A Full but Failed Run.mp4"
  },
  "QhCDXshYUZ": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 334539820,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E35 - Our Server is SO FAST it's UNSTABLE.mp4"
  },
  "Et6fYWHSpc": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 657926929,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E36 - CC Interstellar - It seems like this is everyone's favorite movie I.mp4"
  },
  "ZV8UNWGMWC": {
    "subChannel": "TechLinked",
    "partial": false,
    "saved": true,
    "size": 92487161,
    "file": "./videos/TechLinked/TechLinked - S01E10 - TL GET IT TOGETHER, INTEL!.mp4"
  },
  "U9Qm8IZBu9": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 145556284,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E37 - The Gaming PC that Cools YOU (SPONSORED).mp4"
  },
  "MlwWJkV4Iq": {
    "subChannel": "BitWit Ultra",
    "partial": false,
    "saved": true,
    "size": 362079567,
    "file": "./videos/BitWit Ultra/BitWit Ultra - S01E12 - I need to relax.mp4"
  },
  "rqHSTJr2T0": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 160866418,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E38 - SC New Channel, Who Dis - Pitaka Air Quad.mp4"
  },
  "Ni9ZC08mB1": {
    "subChannel": "BitWit Ultra",
    "partial": false,
    "saved": true,
    "size": 98208384,
    "file": "./videos/BitWit Ultra/BitWit Ultra - S01E13 - 21 questions with Lyle.mp4"
  },
  "nzUKTl2Yq0": {
    "subChannel": "TechLinked",
    "partial": false,
    "saved": true,
    "size": 84627801,
    "file": "./videos/TechLinked/TechLinked - S01E11 - TL This Chinese CPU could be GOOD!.mp4"
  },
  "VCEVpP2Bfl": {
    "subChannel": "LTT Supporter (OG)",
    "partial": false,
    "saved": true,
    "size": 381307864,
    "file": "./videos/LTT Supporter (OG)/LTT Supporter (OG) - S01E39 - Dead CPU Try this!!.mp4"
  }
}

partial.json "{}"

**Comment by jasonteague** [comment]
A workaround for this is to copy the dist folder to lib (doesn't seem to exist by default) within m3u8stream

For example I ran this from within my Floatplane downloader folder:
xcopy /E /I node_modules/m3u8stream/dist node_modules/m3u8stream/lib

**Comment by Inrixia** [comment]
Closing as the module causing the error is no longer used.
