### ISSUE TITLE
Short Circuit and Carpool Critics not sorted

### ISSUE THREAD

**Issue by TomW1605** [Inrixia/Floatplane-Downloader#38]
the script is not sorting Short Circuit or Carpool Critics videos into their own folders

**Comment by Inrixia** [comment]
I dont beleive these have been added yet, next release should have them and also make it easier for users to add new LMG "sub channels" without needing to wait on a release.

**Comment by Inrixia** [comment]
Added a while ago. 
Will be released with v5
