### ISSUE TITLE
REQUEST remove sub channel initials from name

### ISSUE THREAD

**Issue by TomW1605** [Inrixia/Floatplane-Downloader#40]
after being sorted the video files still have the sub channel initials in the name. this is unnesasery and ugly

**Comment by Inrixia** [comment]
Ill look into adding this as a setting in the next release.

**Comment by TomW1605** [comment]
I ended up doing this myself. I just borrowed and modified the code from the part where subchannels are assigned and put it at the beginning of the doTitleFormatting function
```
if(subscription) {
    if(subChannelIdentifiers[subscription.title.toLowerCase()]) {
        subChannelIdentifiers[subscription.title.toLowerCase()].forEach(function(subChannel){
            if(subChannel.type == "title") {
                if (video["title"].toLowerCase().indexOf(subChannel.check) > -1) {
                    var re = new RegExp(subChannel.check,"ig");
                    video.title = video.title.replace(re, '').trim();
                }
            }
        });
    }
}
```
i also had to pass the `subscription` variable to the function

**Comment by Inrixia** [comment]
Added in https://github.com/Inrixia/Floatplane-Downloader/commit/c2db71082a1f6886995f8d2423cd9912a0f36e27
Will be released with v5
