### ISSUE TITLE
ReadError: The server aborted pending request

### ISSUE THREAD

**Issue by Hezkezl** [Inrixia/Floatplane-Downloader#49]
This is the most common problem I run into after the new version update. After a while of downloading videos, it will get roughly halfway (between 40%-50%) through downloading a video when the entire download process will stop and wait for me to close the program when this error pops up. (I'm also unsure if the hard-coded path in the below screenshot helps or hurts anything in the process, but I definitely don't have this thing installed to `c:\snapshot` so I'm assuming it's your path.

https://cdn.discordapp.com/attachments/468978648460820490/819960585113305138/unknown.png

Also I'm not sure if this error is related to total amount of time elapsed when downloading (ie: it errors out after 60 minutes) or if it errors out after X number of files, but this is preventing me from leaving the program running all night to download my whole queue :(

**Comment by Inrixia** [comment]
```c:\snapshot``` is referring to inside the executable and isnt a issue.
I've added soft handling of errors in https://github.com/Inrixia/Floatplane-Downloader/commit/ebd2079cdb48dc49d45b9d8f19eaf6c11fb1e8f0 this will stop the process exiting on failed downloads.

Though I don't know if all videos will fail to download after the error you mention appears or if it will recover, ideally it should just recover as it appears to be a issue on the floatplane api side of things.

**Comment by Inrixia** [comment]
Auto recovery of this error should now work with the changes from https://github.com/Inrixia/Floatplane-Downloader/commit/564f3ce2c98297710124c8a0df000a0b7ed7eef3
