### ISSUE TITLE
Plex username/password is incorrect after selecting "No" to Plex refreshing

### ISSUE THREAD

**Issue by TheSamDickey** [Inrixia/Floatplane-Downloader#50]
Hey one thing I noticed is that it asks whether or not I want to automatically refresh plex libraries.  I selected no, and it still prompted me for my plex credentials.  I left them both blank and said it was incorrect.

Keep up the awesome work though, this is amazing software :D

**Comment by Inrixia** [comment]
Should be fixed in https://github.com/Inrixia/Floatplane-Downloader/commit/eeeb27600fcb988d268afcd58e15541a0f1c5b0a
