### ISSUE TITLE
400/Bad Request Error when 2160p is enabled

### ISSUE THREAD

**Issue by SlyBlueFox** [Inrixia/Floatplane-Downloader#51]
Beta is working great overall so far, one bug I found is when 2160p is enabled. I get HTTP 400 (Bad Request) error for all episodes from the looks of it. Dropping back to 1080p in the config files works as a workaround.
![image](https://user-images.githubusercontent.com/16006024/111056349-85141980-844c-11eb-9a46-098fd8c90d15.png)

**Comment by Inrixia** [comment]
Fixed in https://github.com/Inrixia/Floatplane-Downloader/commit/2c6d585a8a2905b8aa576234a340af18284952e6
