### ISSUE TITLE
Error with FFMPEG

### ISSUE THREAD

**Issue by Hezkezl** [Inrixia/Floatplane-Downloader#53]
![](https://cdn.discordapp.com/attachments/468978648460820490/824010808093966355/unknown.png)

![](https://cdn.discordapp.com/attachments/468978648460820490/824010842256703538/unknown.png)

Had this happen just a few moments ago when running the program.

**Comment by Inrixia** [comment]
Is the video file that's downloaded playable if you rename it to include .mp4 at the end?

**Comment by Hezkezl** [comment]
Nope :( "Cannot render file" if I manually rename it.

(To copy Discord convo to here for archival purposes:)

Downloaded the 720p version, file size was much larger (88mb) and actually played. The 1080p version stops after ~18mb and fails to play, so something failed on Floatplane's end with this video somehow

**Comment by Inrixia** [comment]
As there is no way to reproduce this issue to test as it has been fixed on floatplanes side I'm just going to close this for now.
