### ISSUE TITLE
Unauthorized in login

### ISSUE THREAD

**Issue by PauloDanielCarneiro** [Inrixia/Floatplane-Downloader#55]
When trying to login, got the HTTPError: Response code 401 (Unauthorized).

Checked the password and username in floatplane, and it's not wrong. Probably a change in the login api.

**Comment by Inrixia** [comment]
![image](https://user-images.githubusercontent.com/6373693/113965332-43c32e00-9881-11eb-8a8e-3bab01e77f4d.png)
Looks like something's changed with the api. I'll take a closer look

**Comment by Inrixia** [comment]
Yep, problem related to the new recaptcha implementation on floatplanes side. There was a fix for direct api access but it hasn't been implemented on their side due to time constraints, for now login won't work until I get a workaround or a way to get captcha working.

**Comment by Inrixia** [comment]
Hotfix on the discord, proper fix is waiting on support from the floatplane guys.

**Comment by Inrixia** [comment]
Closing for now as going to use hotfix for the foreseeable future
