### ISSUE TITLE
delete aged videos 

### ISSUE THREAD

**Issue by Adiack06** [Inrixia/Floatplane-Downloader#56]
it would be useful to have a setting to delete videos from certain channels when they are over a certain age 

i would find this useful as excluding vods i am only using this so i can watch stuff on my fire tv and so  save progress in plex as floatplane rather annoyingly doesn't save progress.

**Comment by guitaristtom** [comment]
I agree, this would definitely make me want to use this over just using the Floatplane website.

**Comment by Inrixia** [comment]
Looking to add this soon. What would be better date to use for deletion. When the video was downloaded or when it was released?

**Comment by guitaristtom** [comment]
Probably from when they were released. That way someone can specify "only the last 60 days worth of videos" kind of thing.Although, it could be done in two parts. That way you have the best of both options, but whichever option comes first. On Nov. 5, 2021 21:43, Inrixia ***@***.***> wrote:
Looking to add this soon. What would be better date to use for deletion. When the video was downloaded or when it was released?

**Comment by Inrixia** [comment]
This feature has been added in https://github.com/Inrixia/Floatplane-Downloader/commit/9e8092f87c8a34b01c1433c780a26af83e4aa43e. I have done some tests and it seems stable.

Will be included in the upcoming release, if you want to use it now use the latest/dev release/tag

**Comment by vodkapmp** [comment]
@Inrixia Is this part: 
> from certain channels

Included in the new feature? 
I don't see any way to include/exclude specific channels for this.

**Comment by Inrixia** [comment]
Nope I 100% missed this. Feel free to reopen if you want that extra part added

**Comment by Inrixia** [comment]
Or if you cant let me know and I can

**Comment by vodkapmp** [comment]
> Nope I 100% missed this. Feel free to reopen if you want that extra part added

I can't reopen this issue, so I'd have to open a new issue then. Which I can do if you prefer that.

**Comment by Inrixia** [comment]
Allg I'll reopen it and add the functionality at the subchannels level

**Comment by Inrixia** [comment]
Actually better to open the addition as a separate issue. Please do so and mention this one in its creation @vodkapmp, thanks
