### ISSUE TITLE
Move ffmpeg binary for docker release

### ISSUE THREAD

**Issue by Fma965** [Inrixia/Floatplane-Downloader#57]
As discussed on discord, having the ffmpeg on a user mounted bind is not a great idea, suggest moving it to inside the docker container, things like noexec on moounts can cause issues etc otherwise.

**Comment by Inrixia** [comment]
https://github.com/Inrixia/Floatplane-Downloader/commit/4c86035476598c00331e8200928912a6c64daf6d

Done
