### ISSUE TITLE
Add support for DD-MM-YYYY / YYYY-MM-DD in file names

### ISSUE THREAD

**Issue by vodkapmp** [Inrixia/Floatplane-Downloader#58]
For easier sorting of episodes, using a date based format (DD-MM-YYYY / YYYY-MM-DD) would probably be preferable.

This is also supported by the plex naming convention. As seen under "Date-Based Television Shows" section [here](https://support.plex.tv/articles/naming-and-organizing-your-tv-show-files/)

Using this, there should be no need to do any sort of episode numbering.
This would also work for sorting the files for people not using plex/emby/jellyfin, as they would be sortable by release date if using YYYY-MM-DD format.

**Comment by Inrixia** [comment]
Re testing on discord using the plex Date-Based Television Shows unfortunately does not work as plex only supports going as far as daily episodes while videos from floatplane as sometimes posted within seconds of each other.

What I have done is added support for using %day%, %hour%, %minute% and %second% in the title formatting so you can utilize those for custom formatting options in https://github.com/Inrixia/Floatplane-Downloader/commit/570ad16189f7774ab1886af67cf960e155e68ff4.

I have also set the new default format for episode numbering to be S%year%E%month%%day%%hour%%minute%%second% in https://github.com/Inrixia/Floatplane-Downloader/commit/ea74f7f9bd0a81a40179a32dacba9e57c58333f0 as its much more reliable than using the generated episode number.
