### ISSUE TITLE
Issue with downloading to a NAS

### ISSUE THREAD

**Issue by RevoMarine** [Inrixia/Floatplane-Downloader#6]
Been having issues when downloading straight to a NAS. Either iSCSI share or SMB share it still gives me errors. Downloading straight to folder on the drive it is installed to is fine however.

https://pastebin.com/M2XqRzTd. Here is my pastebin of the errors. 

Thanks!

**Comment by Inrixia** [comment]
Was it previously working or is this a first install?

Also have you tried pointing it at a symlinked folder or a mounted network share as a drive?

**Comment by RevoMarine** [comment]
It works when I change it back to just a folder where it's installed. Haven't adventured to trying to pointing it to somewhere else on the C drive. 
It's pointed to a mounted network share. 
I thought it could be because it is seen as a network drive and not a disk physically on the computer so that's when I tried an iSCSI mount to try it that way and it still didn't work.

**Comment by Inrixia** [comment]
Have you tried syslinking a folder on the nas to your computer drive and then pointing it at that? That should work.

**Comment by RevoMarine** [comment]
Created a syslink from my desktop to the NAS and still got the same error.

Created a syslink from the folder it's installed in to my NAS and it works perfect!

**Comment by RevoMarine** [comment]
Well. I thought it was going to work. Left it for a bit and came back and it crashed again.

**Comment by Inrixia** [comment]
It might be a issue with your nas then. I just tried pointing the script at a network share on one of my servers (Windows) and it works fine...

Can you send me what is actually outputted in the console when running it?

**Comment by RevoMarine** [comment]
https://puu.sh/zMdib/75b6b13da8.png 

That's the output of the command line after starting the batch file.

**Comment by RevoMarine** [comment]
https://puu.sh/zMdn1/28d637dc87.png

Seems like instead of going to that folder, it creates each folder. Should I try it that way? 

Folder for downloading is ./Videos123/

**Comment by RevoMarine** [comment]
Decided to not try it on a VM and it works perfectly. So something to do with that.

**Comment by Inrixia** [comment]
Did you make sure to have a / at the end of the folder path in the settings? Not that it should matter but that's probably why the folders were being called folder123LinusTechTips etc...

Also from what I could see of that error its nothing to do with the storage... Though It looks like it could be to do with it trying to download youtube videos, could you perhaps try to only download the latest video?

**Comment by RevoMarine** [comment]
I was trying to download all of them honestly and I think that's what caused the freak out.

I changed it from 30 pages to 15 and it instantly started working.

**Comment by Inrixia** [comment]
A while ago I added functionality for it to try and download youtube videos if any posts had them (Some posts contained youtube videos because of a simultaneous release or floatplane issue that were never replaced) So It could actually be a issue to do with that If you want I could probably show you how to disable downloading youtube videos to see if it will let you download the entire floatplane archive.

Though to be honest your likely better off just downloading the last week or so worth of floatplane content and then using 4K Downloader to download all of the other videos off youtube. Youtubes 4k has a much higher bitrate than floatplane ATM sadly.

**Comment by RevoMarine** [comment]
Honestly not even sure why I want to download it all, more of just a joke at this point cause I love datahoarding I guess.

But maybe? 1080p is fine for me honestly. But might look in to just downloading the rest from YT although im not sure I can even support their entire YT things lol
