### ISSUE TITLE
reconnecting but not resubscribing afik

### ISSUE THREAD

**Issue by torodiesel** [Inrixia/Floatplane-Downloader#62]
![Capture](https://user-images.githubusercontent.com/52382226/115310315-9c28e400-a13b-11eb-9270-195eab7b0727.PNG)
Was requested to add this to the issues list by Inrixia.

**Comment by Inrixia** [comment]
Pretty sure this was fixed here https://github.com/Inrixia/floatplaneAPI.ts/commit/fce1b7fd6fcb3d4bde8ed1311d0fcd3da7bbfd85 and has been on dev ever since, closing for now let me know if it crops up again once the beta with the fixes is out.
