### ISSUE TITLE
Put links to the poster (thumbnail) images in the Wiki pages. 

### ISSUE THREAD

**Issue by benjisoft** [Inrixia/Floatplane-Downloader#7]
There are some lovely posters but no way of downloading them at the moment.

**Comment by Inrixia** [comment]
What posters are you talking about specifically?

**Comment by benjisoft** [comment]
The ones seen in this screenshot. 
![image](https://user-images.githubusercontent.com/8136412/39597236-a1948a36-4f0c-11e8-9746-5cbfc3184c97.png)

**Comment by Inrixia** [comment]
They are in the videos folder by default when downloading the script under artwork.
