### ISSUE TITLE
Option to keep subchannel prefixes in video title

### ISSUE THREAD

**Issue by peskdale** [Inrixia/Floatplane-Downloader#74]
I'd like an option to be able to keep the subchannel prefixes that are normally stripped as part of the channel identification.

This is currently being removed the video title as part of the channel identification [here](https://github.com/Inrixia/Floatplane-Downloader/blob/master/src/lib/Subscription.ts#L68).

**Comment by Inrixia** [comment]
Added in https://github.com/Inrixia/Floatplane-Downloader/commit/b258e7bea70e35142d6af33b355f2e3310226551

Please test using the latest `dev` release for any unexpected behaviour. <3

**Comment by peskdale** [comment]
I can't seem to get this to work on the dev release. My settings file is as follows:
```
        "extras": {
                "stripSubchannelPrefix": false,
                "downloadArtwork": true,
                "saveNfo": false
        },
```

But the prefix is still being stripped.

**Comment by peskdale** [comment]
Found the issue. PR #76.

**Comment by Inrixia** [comment]
Merged, thanks <3
