### ISSUE TITLE
Ability to change artwork filename / add suffix

### ISSUE THREAD

**Issue by peskdale** [Inrixia/Floatplane-Downloader#75]
Kodi looks for artwork in the format VIDEONAME**-thumb**.png, and so currently ignores the downloaded image.

It would be great to have an option to add a custom suffix string to the already defined filepath.

**Comment by Inrixia** [comment]
Added in https://github.com/Inrixia/Floatplane-Downloader/commit/36005e9e0440ee278d3d76ccc5c5d53cc0f8629b

Please test using the latest `dev` release for any unexpected behaviour. <3

**Comment by peskdale** [comment]
Seems to be working. Thanks!
