### ISSUE TITLE
Error 520 when trying to run

### ISSUE THREAD

**Issue by Hezkezl** [Inrixia/Floatplane-Downloader#77]
As per Discord beta chat talk, I get this error now whenever I try to load the program

![Screenshot](https://cdn.discordapp.com/attachments/468978648460820490/856360436899119134/unknown.png)

**Comment by Inrixia** [comment]
This was a dependency issue. It should be fixed in https://github.com/Inrixia/Floatplane-Downloader/commit/359901fffc59fff5c477b6d2d60ac0d0881f7529
