### ISSUE TITLE
Feature Request: Logging

### ISSUE THREAD

**Issue by rob1998** [Inrixia/Floatplane-Downloader#8]
Would it be possible to log to a file as well?
For example when a video is downloaded or when something errored.
I found this library online: https://github.com/log4js-node/log4js-node

**Comment by Inrixia** [comment]
Sure though I would likely just write the logging myself. Anything specific you would want with the formatting?

I'll add it in the next release

**Comment by rob1998** [comment]
Something like this perhaps:
`[timestamp] level: message`
timestamp and message speak for themself I think
level would be something like: debug, info, error

**Comment by rob1998** [comment]
maybe make a setting for the logfile location as well, not really needed for me atm, but it may be of help to others, or in the future

**Comment by Inrixia** [comment]
Feature added in v4.2.6
