### ISSUE TITLE
postProcessingCommand error handling triggers message every time

### ISSUE THREAD

**Issue by peskdale** [Inrixia/Floatplane-Downloader#80]
Regardless of the actual outcome of a post-processing command, the error message seems to always be triggered after downloading a video.

This can be seen using a very simple command such as `echo 'Hello world!'`. On further testing, it seems that stderr is defined regardless of outcome, but just empty.

So perhaps there should be an emptiness check too, or the check should instead be run based on non-zero exit status.

**Comment by Inrixia** [comment]
This is what I get for not testing properly :)

Ill change the check to a emptiness one rather than if its undefined. I also should have added bar status updates for when its running so Ill do that too.

**Comment by Inrixia** [comment]
Added in https://github.com/Inrixia/Floatplane-Downloader/commit/eb62cd230bc87b00cb83eab8b0902b96f97ccbf0

Please grab the latest dev release and test it to check that the fix is working. The status bar/console should also now indicate when the command is running.

**Comment by peskdale** [comment]
Fix seems to work. Cheers. :+1:
