### ISSUE TITLE
FFMPEG doesn't work if headless = true

### ISSUE THREAD

**Issue by Fma965** [Inrixia/Floatplane-Downloader#82]
looks like it's using the wrong path for ffmpeg
![image](https://user-images.githubusercontent.com/1707290/125614336-c5a78253-bb28-4d57-af6a-0a353b0a1d14.png)

if i set headless to false it works

Looks like you missed a line when fixing this? https://github.com/Inrixia/Floatplane-Downloader/issues/57

i suspect here is your issue https://github.com/Inrixia/Floatplane-Downloader/blob/9dcb6a308616593913299846aff5936c97691286/src/lib/Video.ts#L172

EDIT: i would make a PR but i don't know the syntax of this language.

**Comment by Inrixia** [comment]
Hopefully fixed in https://github.com/Inrixia/Floatplane-Downloader/commit/8e2b3b3a8dc4a7e23372aa8159ee76e9585e36bb let me know.

**Comment by Inrixia** [comment]
@Fma965 Is this fixed?

**Comment by Fma965** [comment]
I haven't tried it. I'd assume so though, consider it solved unless you hear from me in the future ;)

**Comment by AltriusRS** [comment]
I have spent numerous days of solid downloads on headless mode, not ran into it, safe to consider it fixed on the dev branch

**Comment by Inrixia** [comment]
Thanks, considering fixed

**Comment by Fma965** [comment]
BTW this still doesn't work when headless is set to true

**Comment by Inrixia** [comment]
Please try a clean install and let me know if its still not working

**Comment by Fma965** [comment]
define "clean install" in regards to docker

**Comment by Inrixia** [comment]
Either completely delete the container and clear any mounts. Or create a new container with empty mounts. IE no config etc or video files

**Comment by Fma965** [comment]
No luck, same issue

**Comment by Inrixia** [comment]
Are you sure you are running the latest version.
Can I get your logs output and a copy of your settings?

**Comment by Fma965** [comment]
As far as i can tell yes, i'll get a proper output without any complications later today
