### ISSUE TITLE
[Feature] Add ability to pause download queue

### ISSUE THREAD

**Issue by AltriusRS** [Inrixia/Floatplane-Downloader#83]
This feature would ideally pause ongoing downloads, but optionally, or at the developer's discretion it should be able to stop the program moving onto any further video downloads in the queue. One potential method of doing this is to allow the resumption of downloads and video discovery by taking advantage of the `db` directory to store progress and the queue itself. Another would be to provide a hotkey to press to stop the download queue temporarily, and press again to resume.

Please let me know if further explanation is needed!

**Comment by Inrixia** [comment]
Resuming downloads is already supported if you close the downloader mid downloads and then reopen it. Any videos partially downloaded will continue to download from where they left off.

**Comment by AltriusRS** [comment]
good point, I can probably close this issue given that functionality exists via the ctrl+c method haha. Thanks for your time :)
