### ISSUE TITLE
Add ability to manually change the edge server in use

### ISSUE THREAD

**Issue by TheDevilOnHoliday** [Inrixia/Floatplane-Downloader#84]
Add ability to manually change the edge server in use - edge01-na is significantly slower than edge03-na for instance

**Comment by Inrixia** [comment]
Should be added in https://github.com/Inrixia/Floatplane-Downloader/commit/551aae79d55cd8ef8327d0d1dd71f08409d85f97

Please test once its built and let me know.

Thanks

**Comment by TheDevilOnHoliday** [comment]
Hello, yes this worked well, once I figured out to put this in the json:
"floatplane": {
		"downloadEdge": "edge03-na.floatplane.com"
     },

I was able to reach 500Mbps with this compared to 10-20 with edge01-na which seems to always be the default for me.
