### ISSUE TITLE
Get ERR: connect ECONNREFUSED

### ISSUE THREAD

**Issue by Andavin** [Inrixia/Floatplane-Downloader#87]
Since a few days ago, every time I run the downloader it errors out each video download saying one of the following:
```
ERR: connect ECONNREFUSED 144.217.49.155:443 Max Retries! 3/3
ERR: read ECONNRESET Max Retries! 3/3
```
I'm not sure if this is an issue on my end or maybe Floatplane now refusing downloads. I don't see a lot of other people saying anything about this yet so I'm just wondering what I can do to fix it.

![image](https://user-images.githubusercontent.com/15755161/131265521-6c15cbb3-c8fb-41a7-be75-bc190af65690.png)

**Comment by Inrixia** [comment]
Re the discussion on discord in the **#help** channel this is a issue with the floatplane edge servers. Currently only one edge server is working.

If you are using the dev branch you can use the setting
```json
"downloadEdge": "edge03-na.floatplane.com"
```
to use the one edge that's working.

Nothing else can be done until floatplane fixes their edges. But I'll leave this open for now for visibility.

**Comment by Andavin** [comment]
That worked! Thank you
