### ISSUE TITLE
Can you create a tutorial to do this on a NAS?

### ISSUE THREAD

**Issue by QuintonAjStevens** [Inrixia/Floatplane-Downloader#9]
I have a Synology DS218+ and was trying to set this up on it. It seems a lot of the instructions are Windows based, but you also mention it can be done on other operating systems. I was able to get Node.js installed, but I have no way of running the bat or anything of that sort as far as I can see. 

Thank you

**Comment by Inrixia** [comment]
@QuintonAjStevens Do let me know if that solved it for you. Otherwise I am happy to help

**Comment by QuintonAjStevens** [comment]
Hello again, I've managed to make it fairly far, but now it seems to not like my credentials for some reason. 

This is the error I receive: 
```
root@server:/var/services/homes/plex/YouTube/LinusTechTips/Tool# node float.js
> Using saved login data
> Cookie Constructed!
> Saving settings
ERROR> Failed to login please check your login credentials!
/volume1/homes/plex/YouTube/LinusTechTips/Tool/float.js:35
                throw err
                ^

TypeError: JSON.parse(...).forEach is not a function
    at Request._callback (/volume1/homes/plex/YouTube/LinusTechTips/Tool/float.js:347:22)
    at Request.self.callback (/volume1/homes/plex/YouTube/LinusTechTips/Tool/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/volume1/homes/plex/YouTube/LinusTechTips/Tool/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/volume1/homes/plex/YouTube/LinusTechTips/Tool/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

I know with 100% certainty that my login is correct, as I tested it multiple times. I even copied and pasted the email and password into Floatplane.com and also into the settings file (keeping it in the quotations). Floatplane.com works, but not the script. 

It may also be irrelevant, but the folders were made (Linus Tech Tips, BitWit Ultra, Channel Super Fun, etc.) but no videos are in them. 

Let me know what I can do to possibly fix this issue. Thank you.

**Comment by Inrixia** [comment]
Can you try using your email instead of your username or vice versa? Also you can try put your credentials directly into the settings.json to ensure they are correct. Otherwise It's a error on your part or a issue with fp.com.

Ill see if floatplane has changed their login api again. Also feel free to join the discord if you want to talk to me directly. https://discord.gg/aNTyMME

**Comment by Inrixia** [comment]
Looks like floatplane has changed something with the subscriptions API... I'm looking into it now.

**Comment by Inrixia** [comment]
Yea. They have changed how subscription fetching is working. I will fix it when I get home tonight hopefully in 3-4 hours.  If you get on the discord you can probably ask someone for the subscription part of their settings.json. Copying that into yours will let you use the script till I fix it tonight.

**Comment by QuintonAjStevens** [comment]
Oh, okay! Figured I was doing something wrong, looks like maybe not! I'll just go ahead and wait (no rush, either, I'm not sitting on my hands waiting :stuck_out_tongue_closed_eyes: ) 

Besides this, thank you for creating this tool! I, as well as I'm sure many others, appreciate it! Perhaps I will do up a quick white paper on it and send it to you if you want to post it.

**Comment by Inrixia** [comment]
This should be handled with the new v5 documentation.
