### ISSUE TITLE
Reconnect when internet connection lost

### ISSUE THREAD

**Issue by BlackBadPinguin** [Inrixia/Floatplane-Downloader#95]
I think it would be a nice feature, if the script would automatically try to restart the download, instead of just stopping and not proceeding like it now does.

**Comment by Inrixia** [comment]
If downloads fail they are retired until they can complete. If your internet cuts out it shouldn't hang.

Can you provide steps on how to reproduce the issue?

**Comment by BlackBadPinguin** [comment]
I can only reproduce it if my router loses the DSL synchronisation, however, I got this error: [picture](https://cdn.discordapp.com/attachments/468977376794247199/883403963708354581/Screenshot_20210903-192922_Chrome.jpg)

**Comment by Inrixia** [comment]
In this instance you can just put the command to start the downloader in a loop either in Windows or Linux so it will automatically restart it.

Let me know if you would like an example
