### ISSUE TITLE
Live Streams

### ISSUE THREAD

**Issue by Pel1can111** [Inrixia/Floatplane-Downloader#98]
Not sure if this has been asked for or how much work it involves but it would be neat if it could monitor and download live streams when they are started?

I know they have started adding live streams after they air but its super inconsistant and often they arrive very late.

**Comment by Inrixia** [comment]
Is this talking about downloading then while they are live. Or the vod once they go offline?

**Comment by Pel1can111** [comment]
when they are live. Its very rare I catch live streams due to timezones and often miss out. Ideally they would auto add the VOD after every steam but thats been talked about for a long time but seems to still be manual.

**Comment by Inrixia** [comment]
Are there livestreams they don't upload the vods for?

**Comment by Pel1can111** [comment]
Thanks for asigning this to potentially come out in the next release. I've noticed a few dont get VODS but the main problem I find is the delay in adding the VODS. Often I will grab the WAN show from YT then come back at a later date and listen to the pre stream on FP.

**Comment by Inrixia** [comment]
It may take some time. I did look into downloading streams in the past and itl require some new handling and them to be live for me to even test. Plus right now there is no way to determine when they go live without polling floatplane every x seconds. So not ideal but will see

**Comment by Inrixia** [comment]
Due to the complexity of this throwing it on the blacklog for now. Will require testing which I can only do while they are live.

Also due to polling time and no way to detect when they go live beginnings of streams may be cutoff as I don't believe floatplane offers the ability to jump back in time on streams.

**Comment by Inrixia** [comment]
Closing this as its really out of scope and all livestreams now have vods afik.
