### ISSUE TITLE
Text glitch

### ISSUE THREAD

**Issue by CarsonW7** [Inrixia/Floatplane-Downloader#99]
When the text reaches the bottom of the page it starts to jump around. 

https://user-images.githubusercontent.com/93481614/139590053-64b5375d-3f6c-43cd-a15a-4cfc4f6f91ab.MOV

**Comment by Inrixia** [comment]
@Inrixia Need to try updating to `multi-progress-bars@4.0.0-alpha.0` re https://github.com/kamiyo/multi-progress-bars/issues/5 and see if that fixes this.

**Comment by Inrixia** [comment]
@CarsonW7 The dev version is using `4.0.1` for multi-progress-bars. Were you using the latest/dev build of the downloader when you found this or stable?

**Comment by CarsonW7** [comment]
I believe I was using the lates stable version. But unsure?

**Comment by Inrixia** [comment]
Are you running in docker?

**Comment by CarsonW7** [comment]
I am just running the Float-win.exe file for windows.

**Comment by Inrixia** [comment]
Can you try using the dev version? https://github.com/Inrixia/Floatplane-Downloader/releases/tag/dev

**Comment by CarsonW7** [comment]
sure will do.

**Comment by CarsonW7** [comment]
So I downloaded the copy and just replaced the .exe file and it is still happening. not sure if I have to clean start it from scratch.

**Comment by Inrixia** [comment]
Nope, Ill look into it thanks for the help

**Comment by CarsonW7** [comment]
Not a problem. Thank you.

**Comment by Inrixia** [comment]
Waiting on a response from the @kamiyo the `multi-progress-bars` dev in https://github.com/kamiyo/multi-progress-bars/issues/5

**Comment by Inrixia** [comment]
Re https://github.com/Inrixia/Floatplane-Downloader/issues/102 this should now be solved
